"""Small DB-API adapter for the application's static, parameterized SQL.

SQLite remains available for offline development. Production uses PostgreSQL.
No connection URL or query parameters are logged here.
"""
import sqlite3
from contextlib import contextmanager
from .config import settings

WRITE_LOCK = 481920261
SCHEMA_LOCK = 481920262
WORKER_LOCK = 481920263

class Row(dict):
    def __getitem__(self, key):
        return tuple(self.values())[key] if isinstance(key, int) else super().__getitem__(key)

def row_factory(cursor):
    names = [col.name for col in cursor.description] if cursor.description else []
    return lambda values: Row(zip(names, values))

class Database:
    def __init__(self, connection, postgres):
        self.connection = connection
        self.postgres = postgres

    def execute(self, query, params=None):
        # Application queries are static SQL; user values are always parameters.
        if self.postgres and params is not None:
            query = query.replace('?', '%s')
        return self.connection.execute(query, params) if params is not None else self.connection.execute(query)

    def lock(self):
        # Preserve the short read-check-write critical sections formerly guarded
        # by SQLite BEGIN IMMEDIATE. Never hold this lock over a network/AI call.
        if self.postgres:
            self.execute('SELECT pg_advisory_xact_lock(?)', (WRITE_LOCK,))
        else:
            self.execute('BEGIN IMMEDIATE')

    def schema_lock(self):
        if self.postgres:
            self.execute('SELECT pg_advisory_xact_lock(?)', (SCHEMA_LOCK,))

    def executescript(self, script):
        if self.postgres:
            script = script.replace('INTEGER PRIMARY KEY AUTOINCREMENT', 'BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY')
            script = script.replace(' REAL', ' DOUBLE PRECISION')
        for statement in script.split(';'):
            if statement.strip(): self.execute(statement)

    def columns(self, table):
        if table != 'sessions': raise ValueError('Unsupported schema inspection')
        if self.postgres:
            return {r[0] for r in self.execute("SELECT column_name FROM information_schema.columns WHERE table_schema=current_schema() AND table_name=?", (table,))}
        return {r[1] for r in self.execute('PRAGMA table_info(sessions)')}

@contextmanager
def connect():
    postgres = bool(settings.database_url)
    if postgres:
        import psycopg
        conn = psycopg.connect(settings.database_url, row_factory=row_factory, connect_timeout=10)
    else:
        conn = sqlite3.connect(settings.data_dir / 'lumen.db', timeout=30)
        conn.row_factory = sqlite3.Row
        conn.execute('PRAGMA foreign_keys=ON')
    try:
        yield Database(conn, postgres)
        conn.commit()
    except Exception:
        conn.rollback()
        raise
    finally:
        conn.close()

@contextmanager
def worker_guard():
    """One worker across hosts; paid calls are never automatically replayed."""
    if not settings.database_url:
        yield None
        return
    import psycopg
    with psycopg.connect(settings.database_url, autocommit=True, connect_timeout=10) as conn:
        if not conn.execute('SELECT pg_try_advisory_lock(%s)', (WORKER_LOCK,)).fetchone()[0]:
            raise RuntimeError('A Lumen worker is already running')
        yield conn
