import React from 'react';
import {AbsoluteFill,Sequence,staticFile,useCurrentFrame,interpolate} from 'remotion';
import {Audio} from '@remotion/media';
import timing from './timing.json';
export const newTiming=timing;
type Lang='en'|'zh';type Mode='guide'|'walkthrough';
const ink='#17231f',green='#176c4f',muted='#65736c';
const Pill=({children}:{children:React.ReactNode})=><span style={{padding:'12px 20px',background:'#e8f1eb',borderRadius:30,color:green,fontSize:23,fontWeight:650}}>{children}</span>;
function Panel({id,lang,progress,lines}:{id:string;lang:Lang;progress:number;lines:string[]}){
 const t=(en:string,zh:string)=>lang==='en'?en:zh;
 const box:React.CSSProperties={border:'1px solid #dce3de',background:'#f7f9f7',borderRadius:20,padding:24};
 if(['script','rules','settings','start'].includes(id))return <div style={{...box,background:'white'}}><div style={{fontSize:23,color:muted,marginBottom:22}}>{t('PROJECT BRIEF','项目简报')}</div>{lines.map((l,i)=><div key={l} style={{...box,marginBottom:18,borderColor:Math.floor(progress*3)===i?green:'#dce3de',boxShadow:Math.floor(progress*3)===i?'0 0 0 3px #bfe0c9':'none',fontSize:30}}><span style={{fontSize:19,color:muted,display:'block',marginBottom:10}}>{['01','02','03'][i]}</span>{l}</div>)}<div style={{background:ink,color:'white',borderRadius:14,padding:19,textAlign:'center',fontSize:26}}>{id==='settings'?t('Analyze & build my plan','分析并创建剪辑计划'):t('Example input · use your own facts','填写示例 · 请使用自己的事实')}</div></div>;
 if(id==='upload')return <div style={{...box,textAlign:'center',padding:45}}><div style={{fontSize:80,color:green}}>↑</div><h3 style={{fontSize:36}}>{t('Your original video','你的原片')}</h3><p style={{fontSize:26,color:muted}}>MP4 · MOV · WebM</p><div style={{height:12,background:'#dae6de',borderRadius:12,margin:'40px 0 16px',overflow:'hidden'}}><div style={{width:`${Math.min(100,progress*125)}%`,height:'100%',background:green}}/></div><p style={{fontSize:27}}>{progress>.82?t('Upload complete','上传完成'):t('Saving your footage…','正在保存素材…')}</p><Pill>7 min / 250 MB</Pill></div>;
 if(['references','broll','promise','deliver','export'].includes(id))return <div><div style={{...box,background:'white',fontSize:27,marginBottom:22}}>⌕　{t(id==='references'?'Bangkok apartment':id==='broll'?'Bright apartment interior':'Your story, clearly told',id==='references'?'曼谷公寓':id==='broll'?'明亮的公寓室内':'清晰讲述你的故事')}</div><div style={{display:'flex',gap:20}}>{[0,1,2].map(i=><div key={i} style={{flex:1,...box,padding:12,background:'white',borderColor:i===Math.floor(progress*3)%3?green:'#dce3de'}}><div style={{height:215,background:['#cbd9ce','#e5d9c5','#cedce0'][i],borderRadius:12,position:'relative',overflow:'hidden'}}><svg viewBox="0 0 200 230" style={{width:'100%',height:'100%'}}><path d="M0 150 60 90 120 150 170 110 200 150V230H0" fill="#8da995"/><rect x="37" y="75" width="124" height="116" rx="4" fill="#faf7f0"/><rect x="51" y="88" width="45" height="70" fill="#adc4c8"/><rect x="106" y="88" width="41" height="70" fill="#c1d4d1"/><path d="M34 192h132" stroke="#627e6b" strokeWidth="8"/></svg></div><div style={{fontSize:24,padding:'16px 4px'}}>{t(['Layout','Natural light','Details'][i],['户型','自然采光','细节'][i])}</div><Pill>{t('Review','审核')} {i+1}</Pill></div>)}</div><div style={{marginTop:30,fontSize:27,color:muted}}>{id==='export'||id==='deliver'?'Douyin · TikTok · Reels · Shorts · 小红书':t('Illustrated example • verify the real footage','示意案例 · 请核实实际素材')}</div></div>;
 if(id==='audio')return <div style={box}>{['Captions / 字幕','Music / 音乐','Sound / 音效'].map((name,i)=><div key={name} style={{marginBottom:30}}><div style={{fontSize:25,marginBottom:15}}>{name}</div><div style={{height:65,display:'flex',alignItems:'center',gap:5,background:'white',padding:15,borderRadius:12}}>{Array.from({length:44},(_,j)=><div key={j} style={{width:9,height:10+Math.abs(Math.sin(j*1.6+i))*38,background:i===1?'#8c80b7':green,opacity:j/44<progress?1:.3}}/>)}</div></div>)}<Pill>{t('Listen before approving','批准前请试听')}</Pill></div>;
 return <div style={box}><div style={{display:'flex',justifyContent:'space-between',alignItems:'center',marginBottom:30}}><strong style={{fontSize:29}}>Director Timeline</strong><Pill>{t('Review','审核')}</Pill></div><div style={{height:205,background:ink,borderRadius:16,color:'white',display:'flex',alignItems:'center',justifyContent:'center',fontSize:35,position:'relative'}}>{id==='quality'?t('Watch the complete master','完整观看主版本'):t('Your footage • your decisions','你的素材 · 你的决定')}<div style={{position:'absolute',bottom:20,left:25,right:25,height:4,background:'#fff3'}}><div style={{height:'100%',width:`${progress*100}%`,background:'#bdda9a'}}/></div></div><div style={{display:'flex',gap:9,marginTop:27}}>{[0,1,2,3].map(i=><div key={i} style={{flex:i===0?1.3:1,height:80,borderRadius:12,background:i===Math.floor(progress*4)?green:'#c8d9cd',color:i===Math.floor(progress*4)?'white':ink,padding:16,fontSize:24}}>{String(i+1).padStart(2,'0')}<div style={{fontSize:18,marginTop:8}}>00:{String(i*3).padStart(2,'0')}</div></div>)}</div><div style={{display:'flex',gap:12,marginTop:30}}>{[t('Approve','批准'),t('Replace','替换'),t('Lock','锁定')].map((v,i)=><div key={v} style={{...box,padding:'15px 22px',fontSize:24,background:i===0?green:'white',color:i===0?'white':ink}}>{v}</div>)}</div></div>;
}
function Scene({scene,lang,index,total,mode}:{scene:any;lang:Lang;index:number;total:number;mode:Mode}){
 const f=useCurrentFrame();const progress=Math.min(1,f/scene.frames);const active=Math.min(2,Math.floor(progress*3));
 return <AbsoluteFill style={{background:'#f4f6f2',color:ink,fontFamily:'Arial, "PingFang SC", sans-serif',padding:'66px 100px'}}>
 <div style={{display:'flex',justifyContent:'space-between',alignItems:'center'}}><div style={{fontSize:39,fontWeight:750,letterSpacing:-1}}>lumen<span style={{color:green}}>.</span></div><div style={{fontSize:21,color:muted,letterSpacing:2}}>{mode==='guide'?'PRODUCT OVERVIEW / 产品介绍':'WORKFLOW GUIDE / 使用教程'}　{String(index+1).padStart(2,'0')} / {total}</div></div>
 <div style={{display:'grid',gridTemplateColumns:'0.95fr 1.05fr',gap:75,alignItems:'center',height:740,opacity:interpolate(f,[0,12],[0,1],{extrapolateRight:'clamp'}),translate:interpolate(f,[0,18],['0px 18px','0px 0px'],{extrapolateRight:'clamp'})}}>
 <div><div style={{color:green,fontSize:22,fontWeight:650,marginBottom:25}}>{lang==='en'?'LUMEN 3.0 · '+(mode==='guide'?'YOUR EDITING WORKSPACE':'STEP '+(index+1)):'LUMEN 3.0 · '+(mode==='guide'?'你的剪辑工作空间':'第 '+(index+1)+' 步')}</div><h1 style={{fontSize:lang==='en'?67:72,lineHeight:1.12,letterSpacing:-2,margin:'0 0 38px',fontWeight:650}}>{scene.title}</h1>{scene.lines.map((line:string,i:number)=><div key={line} style={{fontSize:28,lineHeight:1.4,padding:'16px 20px',marginBottom:10,borderRadius:14,background:active===i?'#e0eddf':'transparent',color:active===i?ink:muted,display:'flex',gap:14}}><span style={{color:green}}>0{i+1}</span>{line}</div>)}</div>
 <Panel id={scene.id} lang={lang} progress={progress} lines={scene.lines}/></div>
 <div style={{position:'absolute',bottom:28,left:100,right:100,display:'flex',justifyContent:'space-between',fontSize:18,color:muted}}><span>lumen-fix.universalgravity.org</span><span>{lang==='en'?'Illustrated workflow · processing times vary':'流程示意 · 实际处理时间因任务而异'}</span></div>
 <div style={{position:'absolute',bottom:0,left:0,height:5,width:`${(index+progress)/total*100}%`,background:green}}/>
 </AbsoluteFill>
}
export function GuideV5({lang,mode}:{lang:Lang;mode:Mode}){
 const f=useCurrentFrame();const data=timing[lang][mode];const cap=data.captions.find(c=>c.startMs<=f/30*1000&&c.endMs>f/30*1000);
 return <AbsoluteFill>{data.scenes.map((s,i)=><Sequence key={s.id} from={s.fromFrame} durationInFrames={s.frames}><Scene scene={s} lang={lang} index={i} total={data.scenes.length} mode={mode}/><Sequence from={6}><Audio src={staticFile(s.audio)}/></Sequence></Sequence>)}{cap&&<div style={{position:'absolute',bottom:86,left:160,right:160,textAlign:'center',fontFamily:'Arial,"PingFang SC",sans-serif',fontSize:32,lineHeight:1.35,color:ink}}>{cap.text}</div>}</AbsoluteFill>
}
