const {test}=require('node:test');const assert=require('node:assert/strict');const ts=require('typescript');const fs=require('node:fs');const path=require('node:path');const vm=require('node:vm');
const src=path.resolve(__dirname,'../src');const cache={};
function load(name){if(cache[name])return cache[name];const code=ts.transpileModule(fs.readFileSync(path.join(src,name+'.ts'),'utf8'),{compilerOptions:{module:ts.ModuleKind.CommonJS,target:ts.ScriptTarget.ES2022}}).outputText;const exports={};vm.runInNewContext(code,{exports,require:id=>load(id.replace('./',''))});return cache[name]=exports;}
const {translate,readLanguage,contentLanguage}=load('locale');const {ru}=load('ru');
test('interface selection accepts Russian while keeping project language independent',()=>{assert.equal(readLanguage('ru'),'ru');assert.equal(readLanguage('zh'),'zh');assert.equal(readLanguage('bad'),'en');assert.equal(readLanguage(null),'en');assert.equal(contentLanguage('ru'),'en');assert.equal(contentLanguage('zh'),'zh');assert.equal(translate('ru','Change voiceover','更换配音'),'Сменить озвучку');assert.equal(translate('zh','Change voiceover','更换配音'),'更换配音');assert.equal(translate('en','Change voiceover','更换配音'),'Change voiceover');});
test('every main dictionary entry has a non-empty Russian translation',()=>{const {words}=load('i18n');assert.deepEqual(Object.keys(words.ru).sort(),Object.keys(words.en).sort());for(const [key,text]of Object.entries(words.en)){assert.ok(ru[text]?.trim(),key+': '+text);assert.equal(words.ru[key],ru[text]);}});
test('static editor messages and errors have Russian translations',()=>{const messages=new Set();function literal(n){if(ts.isStringLiteralLike(n))messages.add(n.text);else if(ts.isConditionalExpression(n)){literal(n.whenTrue);literal(n.whenFalse)}}
for(const file of fs.readdirSync(src).filter(f=>f.endsWith('.tsx'))){const source=ts.createSourceFile(file,fs.readFileSync(path.join(src,file),'utf8'),99,true,ts.ScriptKind.TSX);function walk(n){if(ts.isCallExpression(n)){const name=n.expression.getText(source);if(name==='t'&&n.arguments.length===2)literal(n.arguments[0]);if(name==='translate'&&n.arguments.length>=3)literal(n.arguments[1]);}if(ts.isArrayLiteralExpression(n)&&n.elements.length===2&&ts.isStringLiteralLike(n.elements[0])&&ts.isStringLiteralLike(n.elements[1])&&/[\u3400-\u9fff]/.test(n.elements[1].text))messages.add(n.elements[0].text);ts.forEachChild(n,walk)}walk(source)}
const missing=[...messages].filter(s=>!ru[s]?.trim());assert.deepEqual(missing,[]);assert.ok(messages.size>650);});
test('Russian written guide shares existing English media timings',()=>{const c=JSON.parse(fs.readFileSync(path.join(src,'tutorial-content.json'),'utf8'));for(const mode of ['guide','walkthrough']){assert.equal(c.ru[mode].seconds,c.en[mode].seconds);assert.deepEqual(c.ru[mode].chapters.map(x=>[x.id,x.start]),c.en[mode].chapters.map(x=>[x.id,x.start]));assert.ok(c.ru[mode].chapters.every(x=>/[А-Яа-я]/.test(x.title+x.text)));}});
