const {chromium}=require(process.env.PLAYWRIGHT_MODULE||'playwright');
const assert=require('node:assert/strict');
const setup=require('./ui-audit-helper.cjs');
(async()=>{const browser=await chromium.launch({channel:'chrome',headless:true});try{
 const {page,data,goto,tool,button,draft,errors,writes}=await setup(browser);
 data.manual.delivery={render_id:data.project.result.render_id,picture_pending:true,rendered_scenes:1,unapproved_scenes:1,separate_audio:true};
 await goto();
 await page.getByText('Edits are not in the final video yet',{exact:true}).waitFor();
 await page.getByText('Voiceover or music was updated separately; that does not apply picture edits.',{exact:true}).waitFor();
 await button('Review edits and create a version').click();
 await page.locator('dialog[open]').waitFor();
 assert.equal(writes.length,0);
 await button('Back to editing').click();
 await tool('Effects');await page.locator('.manual-clip:visible').getByRole('slider',{name:'Zoom (1–3×)'}).fill('1.4');
 assert.equal((await draft()).clips[0].zoom,1.4);
 await button('Discard edits').click();
 data.manual.delivery.picture_pending=false;
 await page.reload();await button('Review and create version').waitFor();
 assert.equal(await page.getByText('Edits are not in the final video yet',{exact:true}).count(),0);
 assert.deepEqual(errors,[]);
 console.log('PASS stale picture + separate audio status, direct review, duration preset/control, current render clears warning');
 }finally{await browser.close()}})().catch(e=>{console.error(e);process.exit(1)});
