const {chromium}=require(process.env.PLAYWRIGHT_MODULE||'playwright');
const assert=require('node:assert/strict');
const id='c'.repeat(32);
const concept='d'.repeat(32);
const item={id,source:'manual',url:'https://example.com/v',creator:'Ada',published_at:Math.floor(Date.now()/1000)-3600,duration:20,caption:'A quiet tour turns at the door.',hashtags:'travel',audio:'Original voice',category:'travel',sample:false,score:42,signals:[{views:1000,likes:80,comments:10,shares:40}],dna:null,concepts:[]};
(async()=>{
 const browser=await chromium.launch({channel:'chrome',headless:true});
 const page=await browser.newPage({viewport:{width:1280,height:900}});
 const errors=[];
 page.on('pageerror',e=>errors.push(e.message));
 await page.addInitScript(()=>localStorage.setItem('lumen_language','en'));
 await page.route('**/api/**',async route=>{
  const path=new URL(route.request().url()).pathname;
  const method=route.request().method();
  if(path==='/api/session')return route.fulfill({json:{email:'qa@example.test'}});
  if(path==='/api/projects')return route.fulfill({json:[]});
  if(path==='/api/trends'&&method==='GET')return route.fulfill({json:{items:[item],samples:[{key:'tiktok',source:'tiktok',creator:'Sample creator',caption:'Someone expects a simple recipe.',category:'food',duration:14,score:61,note:'Sample card. Nothing is fetched from the platform.',published_at:item.published_at}]}});
  if(path==='/api/trends/samples/tiktok')return route.fulfill({json:{...item,id,sample:true,source:'tiktok'}});
  if(path==='/api/trends/'+id&&method==='GET')return route.fulfill({json:item});
  if(path==='/api/trends/'+id+'/analyze')return route.fulfill({json:{...item,dna:{why:'This structure is inferred from the caption and metrics you saved. The reference file was not downloaded or watched.',narrative:'Expectation → interruption → escalation → reaction → punchline',slots:['expectation','interruption','escalation','reaction','punchline'],hook:'Open on a clear expectation.',setup:'',conflict:'',surprise:'',punchline:'',pacing:'',camera:'',editing_rhythm:'Short setup.',text_overlay:'One original line.',audio_role:'',risks:['Do not download the reference and replace faces or voices.']},concepts:[]}});
  if(path==='/api/trends/'+id+'/concepts'&&method==='POST')return route.fulfill({json:{...item,concepts:[{id:concept,kind:'safe',chosen:false,title:'Everyday parody',story:'Keep the beats.',relation:'Original lines.',hook:'',characters:'',scenes:[],dialogue:'Do not reuse the reference caption.',shots:'',duration:20,editing_style:'',risks:[],script:'Keep the beats.'}]}});
  if(path.endsWith('/choose'))return route.fulfill({json:{...item,concepts:[{id:concept,kind:'safe',chosen:true,title:'Everyday parody',story:'Keep the beats.',relation:'Original lines.',hook:'',characters:'',scenes:[],dialogue:'',shots:'',duration:20,editing_style:'',risks:[],script:'A new structure for your own footage.'}]}});
  if(path==='/api/capabilities')return route.fulfill({json:{analysis:false,generation:false,douyin:false}});
  if(path==='/api/auth/config')return route.fulfill({json:{google_ready:true}});
  return route.fulfill({json:{}});
 });
 const base=process.env.WORKSPACE_URL||'http://127.0.0.1:5192';
 await page.goto(base+'/#trends');
 await page.getByRole('heading',{name:'Find a structure. Then tell your own story.'}).waitFor();
 await page.getByText('Sample card. Nothing is fetched from the platform.').waitFor();
 assert.equal(await page.locator('a[href*="tiktok.com"]').count(),0);
 await page.getByRole('button',{name:'Ada'}).click();
 await page.getByRole('button',{name:'Analyze'}).click();
 await page.getByText('not downloaded or watched').waitFor();
 await page.getByRole('button',{name:'Generate parody'}).click();
 await page.getByRole('button',{name:'Use this version'}).click();
 await page.getByRole('button',{name:'Create with Lumen'}).click();
 await page.locator('input[name=title]').waitFor();
 assert.equal(await page.locator('input[name=title]').inputValue(),'Everyday parody');
 assert.match(await page.locator('textarea[name=script]').inputValue(),/own footage/);
 await page.getByRole('button',{name:'New project'}).click();
 await page.locator('input[name=title]').waitFor();
 assert.equal(await page.locator('input[name=title]').inputValue(),'');
 assert.deepEqual(errors,[]);
 await page.screenshot({path:'/tmp/lumen-trends.png'});
 await browser.close();
 console.log('PASS trends flow');
})().catch(error=>{console.error(error);process.exit(1)});
