import {useState} from 'react';
import type {Lang} from './types';
import type {Edit} from './ManualEditor';
type Preview={revision:number;edit:Edit;changes:{from_output:number;to_output:number}[]};
export function BeatPreview({pid,revision,lang,disabled,onPreview}:{pid:string;revision:number;lang:Lang;disabled:boolean;onPreview:(edit:Edit)=>void}){
 const t=(en:string,zh:string)=>lang==='zh'?zh:en;
 const [result,setResult]=useState<Preview|null>(null),[busy,setBusy]=useState(false),[error,setError]=useState('');
 async function preview(){setBusy(true);setError('');setResult(null);try{const r=await fetch(`/api/studio/projects/${pid}/manual/beat-preview`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({revision})});if(!r.ok){const d=await r.json();throw Error(d.detail==='analyze_rhythm_first'?t('Analyze this music track’s rhythm first.','请先分析此音乐的节奏。'):d.detail==='approve_shots_first'?t('Review and approve all shots, then save first.','请先审核并批准所有镜头，然后保存。'):t('Save your current plan and selected music first.','请先保存当前计划和选定音乐。'))}setResult(await r.json())}catch(e){setError((e as Error).message)}finally{setBusy(false)}}
 return <details><summary>{t('Align safe cuts with music','将安全切点与音乐对齐')}</summary><p>{t('Suggest shifts of up to 0.35 seconds near measured accents. Only adjacent source cuts without timed overlays can move. Speech, locked shots, source coverage and total duration are preserved. No AI charge.','在检测到的重音附近建议最多 0.35 秒的调整。仅移动无定时叠加的相邻原片切点，保留讲话、锁定镜头、素材范围和总时长。不收取 AI 费用。')}</p><button type="button" disabled={disabled||busy} onClick={()=>void preview()}>{t('Find safe beat edits','查找安全节拍剪辑')}</button>{error&&<p role="alert">{error}</p>}{result&&<>{result.changes.length?<><ul>{result.changes.map((c,i)=><li key={i}>{c.from_output.toFixed(2)}s → {c.to_output.toFixed(2)}s</li>)}</ul><button type="button" disabled={disabled||busy||result.revision!==revision} onClick={()=>{onPreview(result.edit);setResult(null)}}>{t('Add to draft for review','加入草稿并审核')}</button><p>{t('Changed shots need approval again. Save and render to hear the result.','已修改镜头需重新批准。保存并渲染后试听结果。')}</p></>:<p>{t('No safe alignment found. The current edit stays unchanged.','未找到安全的对齐方案，当前剪辑保持不变。')}</p>}</>}</details>
}
