import {StatusBadge,UploadProgress} from './TaskStatus';
import {useEffect,useImperativeHandle,useRef,useState,type Ref} from 'react';
import {uploadVideo} from './resumableUpload';
import type {Lang} from './types';
export type Asset={id:string;title:string;attribution:string;metadata:{duration:number;kind?:string;rhythm?:{version:number;accents:number[];bpm:number|null;regularity:number}}};
export type ExternalBroll={asset_id:string;start:number;end:number;source_start:number};
export type MediaLibraryHandle={openMusicUpload:()=>void};
export function MediaLibrary({pid,lang,assets,onChanged,ref}:{pid:string;lang:Lang;assets:Asset[];onChanged:()=>Promise<void>;ref?:Ref<MediaLibraryHandle>}){
 const t=(en:string,zh:string)=>lang==='zh'?zh:en;
 const [kind,setKind]=useState<'video'|'music'>('video');
 const [file,setFile]=useState<File|null>(null),[rights,setRights]=useState(false),[attribution,setAttribution]=useState(''),[busy,setBusy]=useState(false),[percent,setPercent]=useState(0),[error,setError]=useState(''),[outcome,setOutcome]=useState(''),[transfer,setTransfer]=useState<{bytes:number;total:number;mbps:number}>();
 const fileInput=useRef<HTMLInputElement|null>(null);
 const controller=useRef<AbortController|null>(null);
 const library=useRef<HTMLDetailsElement|null>(null);
 useImperativeHandle(ref,()=>({openMusicUpload(){
  if(library.current){library.current.open=true;library.current.scrollIntoView({block:'center',behavior:'smooth'})}
  if(busy)return;
  if(kind!=='music'){setKind('music');setFile(null)}
  requestAnimationFrame(()=>fileInput.current?.focus({preventScroll:true}));
 }}),[busy,kind]);
 useEffect(()=>()=>controller.current?.abort(),[]);
 async function upload(){if(!file)return;setError('');setOutcome('');if(file.size>250*1024*1024){setError(t('Maximum 250 MB.','最大 250 MB。'));return}setBusy(true);setPercent(0);controller.current=new AbortController();try{await uploadVideo(file,{kind,asset_project_id:pid,request_id:crypto.randomUUID().replaceAll('-',''),title:file.name.slice(0,120),attribution,owned_rights_confirmed:rights},controller.current.signal,(n,info)=>{setPercent(n);setTransfer(info)});await onChanged();setFile(null);if(fileInput.current)fileInput.current.value='';setOutcome('uploaded')}catch(e){const code=e instanceof Error?e.message:'';setOutcome(code==='upload_cancelled'?'paused':'failed');setError(code==='asset_duration'?t('Use media between 0.1 and 420 seconds.','请使用 0.1–420 秒的媒体文件。'):code==='asset_limit'?t('Maximum 20 assets per project.','每个项目最多 20 个素材。'):code==='upload_cancelled'?t('Paused. Select upload again to resume.','已暂停。再次点击上传即可继续。'):t('Upload could not finish. Check the media file and retry; saved chunks can resume.','上传未完成。请检查媒体文件并重试，可继续上传已保存的部分。'))}finally{setBusy(false)}}
 return <details ref={library} className="media-library"><summary>{t('Video & music library','视频与音乐素材库')} · {assets.length}/20</summary><p>{t('Upload video or music you own or are licensed to use. Add video to a clip or choose a music track below. Uploading does not change your edit.','请上传自有或获授权的视频或音乐。在下方选择镜头素材或背景音乐；上传不会更改剪辑。')}</p><fieldset disabled={busy}><label>{t('Asset type','素材类型')}<select value={kind} onChange={e=>{setKind(e.target.value as 'video'|'music');setFile(null)}}><option value="video">{t('Video / B-roll','视频／补充镜头')}</option><option value="music">{t('Music','音乐')}</option></select></label><label>{t('Media file (up to 250 MB, 7 minutes)','媒体文件（最多 250 MB、7 分钟）')}<input ref={fileInput} className="director-file-input" type="file" key={kind} accept={kind==='music'?'.mp3,.wav,.m4a,.flac,.ogg':'video/mp4,video/quicktime,video/webm'} onChange={e=>setFile(e.target.files?.[0]||null)}/></label><label>{t('Source / license attribution','来源／授权说明')}<input maxLength={1000} value={attribution} onChange={e=>setAttribution(e.target.value)}/></label><label><input type="checkbox" checked={rights} onChange={e=>setRights(e.target.checked)}/>{t('I have permission to use this footage.','我拥有使用此素材的权限。')}</label></fieldset>{busy?<><UploadProgress percent={percent} lang={lang} bytes={transfer?.bytes} total={transfer?.total} mbps={transfer?.mbps}/><button type="button" onClick={()=>controller.current?.abort()}>{t('Pause upload','暂停上传')}</button></>:<button type="button" disabled={!file||!rights||!attribution.trim()||assets.length>=20} onClick={upload}>{t('Upload to library','上传至素材库')}</button>}{!busy&&<p>{assets.length>=20?t('Library is full: maximum 20 assets.','素材库已满：最多 20 个素材。'):!file?t('Choose a file to upload.','请选择上传文件。'):!attribution.trim()?t('Add the source or license information.','请填写来源或授权说明。'):!rights?t('Confirm permission to enable upload.','请确认使用权限后上传。'):t('Ready to upload.','可以上传。')}</p>}{outcome&&<p role="status"><StatusBadge status={outcome}>{outcome==='uploaded'?t('Uploaded successfully — ready to use','上传成功 — 可以使用'):outcome==='paused'?t('Upload paused','上传已暂停'):t('Upload failed','上传失败')}</StatusBadge></p>}{error&&<p role={outcome==='paused'?'status':'alert'}>{error}</p>}<div className="manual-grid">{assets.map(a=><article key={a.id}><strong>{a.title}</strong>{a.metadata.kind==='music'?<audio controls preload="none" src={`/api/studio/projects/${pid}/assets/${a.id}/media`}/>:<video controls muted preload="none" style={{width:'100%',maxHeight:180}} src={`/api/studio/projects/${pid}/assets/${a.id}/media`}/>}<small>{a.metadata.duration.toFixed(1)}s · {a.attribution}</small></article>)}</div></details>
}
export function AssetPlacement({value,assets,duration,lang,onChange}:{value:ExternalBroll|null;assets:Asset[];duration:number;lang:Lang;onChange:(v:ExternalBroll|null)=>void}){
 const t=(en:string,zh:string)=>lang==='zh'?zh:en;
 return <details><summary>{t('B-roll from media library','素材库中的补充镜头')}</summary><label>{t('Choose footage','选择素材')}<select value={value?.asset_id||''} onChange={e=>{const a=assets.find(x=>x.id===e.target.value);onChange(a?{asset_id:a.id,start:0,end:Math.min(3,duration,a.metadata.duration),source_start:0}:null)}}><option value="">{t('None','无')}</option>{assets.map(a=><option key={a.id} value={a.id}>{a.title}</option>)}</select></label>{value&&<div className="manual-grid">{(['start','end','source_start'] as const).map(k=><label key={k}>{{start:t('Insert starts at (clip seconds)','插入开始（片段秒数）'),end:t('Insert ends at (clip seconds)','插入结束（片段秒数）'),source_start:t('Footage starts at (asset seconds)','素材开始（素材秒数）')}[k]}<input type="number" min="0" step="0.1" value={value[k]} onChange={e=>onChange({...value,[k]:Number(e.target.value)})}/></label>)}</div>}<p>{t('Original speech continues. Choosing library footage replaces any source cutaway on this clip.','保留原有讲话。选择素材库画面将替换该片段中的原片补充镜头。')}</p></details>
}
