import {useEffect,useState} from 'react';
import type {Asset} from './MediaLibrary';
import type {Music} from './MusicEditor';
import type {Lang} from './types';
import {StatusBadge} from './TaskStatus';
type Text={en:string;zh:string};
type Plan={id:string;revision:number;status:string;result:null|{music:Music|null;reason:Text;emotional_curve:Text[]}};
export function MusicPlan({pid,revision,assets,lang,disabled,onApplied,currentMusic}:{currentMusic?:Music|null;pid:string;revision:number;assets:Asset[];lang:Lang;disabled:boolean;onApplied:()=>Promise<void>}){
 const t=(en:string,zh:string)=>lang==='zh'?zh:en,url=`/api/studio/projects/${pid}/music-plans`;
 const [chosen,setChosen]=useState<string[]>([]),[direction,setDirection]=useState(''),[items,setItems]=useState<Plan[]>([]),[busy,setBusy]=useState(false),[error,setError]=useState('');
 async function load(){const r=await fetch(url);if(r.ok)setItems(await r.json())}
 useEffect(()=>{let active=true;async function poll(){try{const r=await fetch(url);if(r.ok&&active)setItems(await r.json())}catch{}}void poll();const timer=setInterval(poll,4000);return()=>{active=false;clearInterval(timer)}},[url]);
 const [mode,setMode]=useState<'select'|'mix_only'>('select');
 const pending=items.some(i=>i.status==='queued');
 async function act(id?:string){setBusy(true);setError('');try{const r=await fetch(url+(id?`/${id}/accept`:''),{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(id?{revision}:{revision,asset_ids:mode==='mix_only'?[]:chosen,direction,mode})});if(!r.ok)throw Error();await load();if(id)await onApplied()}catch{setError(t('Save the latest edit, unlock music and wait for running work to finish.','请保存最新剪辑、解锁音乐并等待当前任务完成。'))}finally{setBusy(false)}}
 return <details className="director-card"><summary>{t('AI soundtrack selection','AI 配乐选择')}</summary><p>{t('Choose up to three licensed tracks. AI measures track-wide rises, drops and quiet sections, listens to selected samples, and maps its proposal to your approved scene order and creator profile. It proposes music and a volume curve; your current edit stays unchanged until you apply it. Reserves up to $0.50 within the project budget.','选择最多三首获授权的音乐。AI 测量整首音乐的强弱变化与安静段落，试听选定片段，并根据已批准的镜头顺序和作者风格推荐配乐及音量曲线。应用前不改变当前剪辑。项目预算内预留最多 $0.50。')}</p><label>{t('Task','任务')}<select disabled={disabled||busy||pending} value={mode} onChange={e=>setMode(e.target.value as 'select'|'mix_only')}><option value="select">{t('Choose a soundtrack','选择配乐')}</option><option value="mix_only" disabled={!currentMusic}>{t('Improve current mix — keep track and alignment','改善当前混音 — 保留曲目与起点')}</option></select></label>{mode==='mix_only'&&<p>{t('Keeps the saved track and start point. AI may adjust volume, fades and ducking; review before applying.','保留已保存的曲目和起点。AI 可调整音量、淡入淡出及压低配乐，请审核后应用。')}</p>}{mode==='select'&&assets.map(a=><label key={a.id}><input type="checkbox" disabled={disabled||busy||pending||(!chosen.includes(a.id)&&chosen.length>=3)} checked={chosen.includes(a.id)} onChange={e=>setChosen(ids=>e.target.checked?[...ids,a.id]:ids.filter(id=>id!==a.id))}/>{a.title}</label>)}{assets.length===0&&<p>{t('Upload music to the library first.','请先上传音乐到素材库。')}</p>}<label>{t('Musical direction','配乐方向')}<textarea value={direction} maxLength={1200} onChange={e=>setDirection(e.target.value)}/></label><button type="button" disabled={disabled||busy||pending||(mode==='select'?chosen.length===0:!currentMusic)} onClick={()=>void act()}>{mode==='mix_only'?t('Suggest mix improvements','推荐混音改进'):t('Suggest a soundtrack','推荐配乐')}</button>{error&&<p role="alert">{error}</p>}{items.slice(0,1).map(item=><article key={item.id}><StatusBadge status={item.status}>{item.status==='queued'?t('Listening and planning…','正在试听并规划…'):item.status==='failed'?t('Music planning failed; your edit is preserved','配乐规划失败，原剪辑保留'):item.status==='accepted'?t('Music applied to the saved plan','配乐已应用到保存的计划'):t('Soundtrack proposal','配乐建议')}</StatusBadge>{item.result&&<><p>{item.result.reason[lang]}</p>{item.result.emotional_curve.map((point,i)=><p key={i}>{point[lang]}</p>)}{item.result.music?<><audio controls preload="none" src={`/api/studio/projects/${pid}/assets/${item.result.music.asset_id}/media`}/><p>{t('Preview is the source track; render to hear the proposed mix.','此为原曲试听，渲染后可听到建议混音。')}</p>{item.status==='ready'&&<button disabled={disabled||busy||pending||item.revision!==revision} onClick={()=>void act(item.id)}>{t('Apply music proposal','应用配乐建议')}</button>}</>:<p>{t('No suitable track found.','未找到合适曲目。')}</p>}</>}</article>)}</details>
}
