// Russian interface messages keyed by their English source. Generated project content is separate.
export const ru: Record<string, string> = {
  "Play": "Смотреть",
  "Preview video": "Предпросмотр",
  " Burn edited subtitles into the video": " Встроить отредактированные субтитры в видео",
  " Normalize overall audio loudness": " Выровнять общую громкость",
  "1. Arrange clips, crop and add text": "1. Расставьте клипы, настройте кадрирование и текст",
  "1. Your references": "1. Ваши референсы",
  "2. Edit subtitles and styling": "2. Отредактируйте субтитры и оформление",
  "2. Your own footage & script": "2. Ваше видео и сценарий",
  "3. Creator & brand profile": "3. Профиль автора и бренда",
  "A clearer view.\nA stronger story.": "Яснее идея. Сильнее история.",
  "A close look at your visuals, voice, pacing and message.": "Подробный разбор изображения, речи, темпа и смысла.",
  "A cut splits a spoken phrase. Adjust the cut to preserve the complete phrase, then render again.": "Монтаж обрывает фразу. Сохраните её целиком и повторите рендер.",
  "A fresh canvas for your next story.": "Место для вашей следующей истории.",
  "A job is already running for this project.": "В этом проекте уже выполняется задача.",
  "A new cut, checked for clarity, continuity and craft.": "Новый монтаж с проверкой ясности, связности и качества.",
  "A private workspace. Sign in with your approved Google account.": "Закрытое рабочее пространство. Войдите через разрешённый аккаунт Google.",
  "A translated phrase could not fit without excessive speed. Your Master is unchanged. Try another voice.": "Переведённая фраза не помещается без чрезмерного ускорения. Основная версия сохранена. Попробуйте другой голос.",
  "AI alternatives": "Варианты от AI",
  "AI budget for this project (USD)": "Бюджет AI для проекта (USD)",
  "AI budget per project": "Бюджет AI на проект",
  "AI can propose a number, comparison, chart, ranking or event timeline using your script and transcript. Include the source and exact values in your feedback. Review all facts before approval.": "AI может предложить число, сравнение, диаграмму, рейтинг или хронологию по вашему сценарию и расшифровке. Укажите источник и точные значения в пожеланиях. Проверьте факты перед утверждением.",
  "AI editorial judgments, not measured audience performance.": "Редакторская оценка AI, а не измеренные показатели аудитории.",
  "AI editorial score": "Редакторская оценка AI",
  "AI footage is disabled for this project": "Генерация видео отключена для этого проекта",
  "AI proposes a replacement for this clip only. Review it before replacing; then approve it separately. Each editing call reserves $0.50, with at most one repair within the project budget. Generating B-roll reserves $1.60 for a four-second illustration. The project budget applies.": "AI предлагает замену только этого клипа. Проверьте её перед заменой и отдельно утвердите. Каждый запрос резервирует $0,50; допускается одна попытка исправления в рамках бюджета. Генерация четырёхсекундной перебивки резервирует $1,60. Действует бюджет проекта.",
  "AI review passed": "Проверка AI пройдена",
  "AI review passed — check the final cut yourself.": "Проверка AI пройдена — просмотрите финальное видео сами.",
  "AI review unavailable": "Проверка AI недоступна",
  "AI searches Commons, ranks up to 24 candidates for this scene and filters weak matches. Two AI stages, each with at most one repair; each call reserves $0.50 within your project budget. Results use metadata: preview and verify footage before use.": "AI ищет в Commons, оценивает до 24 кандидатов для сцены и отсеивает слабые совпадения. Два этапа AI, на каждом допускается одно исправление; каждый запрос резервирует $0,50 из бюджета проекта. Подбор основан на метаданных: просмотрите и проверьте видео перед использованием.",
  "AI selects and orders complete scenes independently. If your footage cannot support a structure, the proposal explains the limitation. Review meaning and continuity before approving.": "AI самостоятельно выбирает и упорядочивает целые сцены. Если материал не подходит для выбранной структуры, предложение объяснит ограничение. Проверьте смысл и связность перед утверждением.",
  "AI selects complete scenes within these limits. You can adjust ranges afterward. YouTube Shorts stays square or vertical and at most 180 seconds.": "AI выбирает целые сцены в указанных пределах. Диапазоны можно изменить позже. YouTube Shorts остаётся квадратным или вертикальным, длительностью до 180 секунд.",
  "AI soundtrack selection": "Подбор музыки с AI",
  "AI usage": "Расходы на AI",
  "AI usage / limit · reservations included": "Расходы AI / лимит · с учётом резервов",
  "AI voice": "AI-голос",
  "AI voiceover — review pronunciation and timing before sharing.": "AI-озвучка — проверьте произношение и синхронизацию перед публикацией.",
  "AI: find B-roll for this scene": "AI: найти перебивку для сцены",
  "Add clip from source": "Добавить клип из исходника",
  "Add cutaway": "Добавить перебивку",
  "Add event": "Добавить событие",
  "Add location": "Добавить место",
  "Add range": "Добавить диапазон",
  "Add reference": "Добавить референс",
  "Add references from the search above. These teach Lumen editing techniques, not what footage to copy.": "Добавьте референсы из поиска выше. Они помогают Lumen изучить приёмы монтажа, а не копировать чужие кадры.",
  "Add row": "Добавить строку",
  "Add sound accent": "Добавить звуковой акцент",
  "Add subtitle": "Добавить субтитр",
  "Add the source or license information.": "Укажите источник или сведения о лицензии.",
  "Add to draft for review": "Добавить в черновик для проверки",
  "Add volume point": "Добавить точку громкости",
  "Added": "Добавлено",
  "Added to editor — approve individual shots": "Добавлено в редактор — утвердите отдельные кадры",
  "Added to library": "Добавлено в медиатеку",
  "Additional cleanup controls": "Дополнительные настройки",
  "Adjusts overall mixed-track loudness only.": "Выравнивает только общую громкость смешанной дорожки.",
  "Adjusts overall mixed-track loudness. Does not separate or rebalance voice and music.": "Выравнивает общую громкость смешанной дорожки. Не разделяет речь и музыку и не меняет их баланс.",
  "After": "После",
  "After analysis, Lumen automatically turns reference techniques into concrete decisions for your footage. Each decision explains what changes, where, and why.": "После анализа Lumen превращает приёмы из референсов в конкретные решения для вашего видео. Каждое решение объясняет, что, где и зачем изменится.",
  "Align an accent to the first approved cut": "Совместить акцент с первой утверждённой склейкой",
  "Align safe cuts with music": "Подстроить безопасные склейки под музыку",
  "All bytes received. Preparing the next step…": "Все данные получены. Подготовка следующего шага…",
  "All proposed shots are visible. Amber shots still need approval and are excluded from rendering. Click a shot to review or edit it.": "Показаны все предложенные кадры. Кадры с жёлтой отметкой требуют утверждения и не попадут в рендер. Нажмите на кадр для проверки или редактирования.",
  "All shots approved and saved. Ready to render.": "Все кадры утверждены и сохранены. Можно запускать рендер.",
  "All times below refer to your owned footage. Approve changes, adjust their ranges, and lock decisions you want to preserve. Unlock and save before changing a locked decision.": "Все таймкоды ниже относятся к вашему исходнику. Утверждайте изменения, правьте диапазоны и закрепляйте решения. Перед изменением закреплённого решения разблокируйте его и сохраните.",
  "Allow AI-generated inserts": "Разрешить вставки, созданные AI",
  "Allow AI-generated supporting footage": "Разрешить создание дополнительных кадров с AI",
  "Already aligned": "Уже выровнено",
  "Already have an account? Sign in": "Уже есть аккаунт? Войти",
  "An AI provider needs to be configured.": "Нужно настроить сервис AI.",
  "An improvement draft has been requested. Review it in Editing decisions from your Video DNA.": "Запрошен черновик улучшений. Проверьте его в разделе решений на основе видеореференсов.",
  "Analysis complete — review decisions": "Анализ завершён — проверьте решения",
  "Analysis ready": "Анализ готов",
  "Analysis, generation and review share this limit. No automatic paid retries.": "Анализ, генерация и проверка используют общий лимит. Автоматических платных повторов нет.",
  "Analyze & build my plan": "Проанализировать и составить план",
  "Analyze music rhythm": "Проанализировать ритм музыки",
  "Analyze this music track’s rhythm first.": "Сначала проанализируйте ритм этой композиции.",
  "Analyze video": "Проанализировать видео",
  "Analyzing": "Анализ",
  "Analyzing reference techniques": "Анализ приёмов референсов",
  "Analyzing rhythm…": "Анализ ритма…",
  "Animated bars": "Анимированные столбцы",
  "Animation duration (seconds)": "Длительность анимации (секунды)",
  "Any time": "За всё время",
  "Applied to plan; review before rendering.": "Применено к плану; проверьте перед рендером.",
  "Applies short fades at repeat boundaries only when the selected excerpt is shorter than the video. Keeps beat timing; does not repair a musical phrase or match different melodies.": "Добавляет короткие затухания на границах повторов, только если выбранный фрагмент короче видео. Сохраняет ритм; не исправляет музыкальную фразу и не согласует разные мелодии.",
  "Applies to the entire clip.": "Применяется ко всему клипу.",
  "Apply music proposal": "Применить музыкальное предложение",
  "Apply only high-confidence recommendations that preserve your message.": "Применять только уверенные рекомендации, сохраняющие смысл.",
  "Applying…": "Применение…",
  "Approve": "Утвердить",
  "Approve a change before locking it.": "Утвердите изменение перед закреплением.",
  "Approve at least one change before rendering.": "Утвердите хотя бы одно изменение перед рендером.",
  "Approve each shot, then save your edits.": "Утвердите каждый кадр и сохраните изменения.",
  "Approve this change": "Утвердить изменение",
  "Approve this version": "Утвердить версию",
  "Approved": "Утверждено",
  "Approved output": "Утверждённый результат",
  "Approved · locked": "Утверждено · закреплено",
  "Archival footage": "Архивные кадры",
  "Asset type": "Тип материала",
  "At least 10 characters": "Не менее 10 символов",
  "Audience": "Аудитория",
  "Audience & intent": "Аудитория и цель",
  "Audio": "Звук",
  "Audio normalization": "Нормализация звука",
  "Automatically create an improved cut after analysis": "Автоматически создать улучшенную версию после анализа",
  "Automatically create the first cut": "Автоматически создать первый монтаж",
  "Average shot": "Средняя длительность кадра",
  "B-roll": "Перебивка",
  "B-roll / cutaway": "Дополнительные кадры / перебивка",
  "B-roll from media library": "Перебивка из медиатеки",
  "B-roll from your source": "Перебивка из исходного видео",
  "B-roll insert": "Вставка дополнительных кадров",
  "Back": "Назад",
  "Background music": "Фоновая музыка",
  "Background panel": "Фоновая плашка",
  "Balanced": "Сбалансированный",
  "Balanced · aim for 3–7 s shots": "Сбалансированный · кадры по 3–7 с",
  "Bar animation": "Анимация столбцов",
  "Bar chart": "Столбчатая диаграмма",
  "Before": "До",
  "Bold": "Выразительный",
  "Bottom": "Снизу",
  "Brand rules & claims to avoid": "Правила бренда и недопустимые утверждения",
  "Budget": "Бюджет",
  "Build a separate manual cut from your footage. Its clip order and settings replace the AI edits for this render; the AI plan remains available. Saving is free. Rendering uses no AI calls and requires your visual review.": "Создайте отдельный ручной монтаж из своего материала. Порядок клипов и настройки заменят AI-правки в этом рендере; план AI останется доступен. Сохранение бесплатно. Рендер не вызывает AI и требует вашей визуальной проверки.",
  "Build timeline from approved AI edits": "Создать таймлайн из утверждённых AI-правок",
  "Building the edit…": "Подготовка монтажа…",
  "Building your Director Timeline": "Создание монтажного таймлайна",
  "Building your edit plan": "Составление плана монтажа",
  "Built around your footage": "На основе ваших материалов",
  "Call to action": "Призыв к действию",
  "Calm · aim for 6–12 s shots": "Спокойный · кадры по 6–12 с",
  "Camera motion: end framing": "Движение камеры: конечный кадр",
  "Camera movement": "Движение камеры",
  "Cancel": "Отмена",
  "Candidates assessed": "Проверено кандидатов",
  "Caption language": "Язык субтитров",
  "Caption mode": "Режим субтитров",
  "Captions": "Субтитры",
  "Captions added": "Субтитры добавлены",
  "Captions for this platform": "Субтитры для этой платформы",
  "Captions off": "Субтитры выключены",
  "Captions on": "Субтитры включены",
  "Card ends at (clip seconds)": "Конец карточки (секунды клипа)",
  "Card starts at (clip seconds)": "Начало карточки (секунды клипа)",
  "Card type": "Тип карточки",
  "Center": "По центру",
  "Change": "Изменение",
  "Change file": "Выбрать другой файл",
  "Change voiceover": "Сменить озвучку",
  "Changed shots need approval again. Save and render to hear the result.": "Изменённые кадры нужно утвердить заново. Сохраните и выполните рендер, чтобы услышать результат.",
  "Changes affect Lumen captions only. Text already in the source video stays visible. Check for overlap with your title.": "Изменения затрагивают только субтитры Lumen. Встроенный текст исходника останется видимым. Проверьте, не перекрывает ли его заголовок.",
  "Changes create a new package. Other videos and their approvals remain unchanged. No AI planning charge for manual edits.": "Изменения создадут новый пакет. Другие видео и их утверждения сохранятся. Ручные правки не требуют оплаты AI-планирования.",
  "Changes present in the timeline": "Изменения в таймлайне",
  "Changing this shot’s timing, picture or effects clears its approval. Review and approve it again before rendering.": "Изменение времени, изображения или эффектов снимает утверждение кадра. Проверьте и утвердите его снова перед рендером.",
  "Check clip/subtitle/card/B-roll/sound ranges and fill all card fields in both languages. Enabled subtitles need at least one entry.": "Проверьте диапазоны клипов, субтитров, карточек, перебивок и звуков. Заполните поля карточек на обоих языках. Для включённых субтитров нужна хотя бы одна запись.",
  "Check the fields and rights confirmation.": "Проверьте поля и подтверждение прав.",
  "Check the start and end times.": "Проверьте время начала и конца.",
  "Check time ranges, subtitle text and whether another job is running.": "Проверьте диапазоны, текст субтитров и наличие других выполняющихся задач.",
  "Checking the finished video": "Проверка готового видео",
  "Chime": "Перезвон",
  "Choose 1–3 assets. AI checks up to five windows per asset, up to four seconds each. Short assets may be covered fully; longer assets are sampled across their duration. It may find no suitable match. Selected samples are sent to the configured AI service.": "Выберите 1–3 материала. AI проверит до пяти фрагментов каждого, до четырёх секунд на фрагмент. Короткие материалы могут проверяться целиком; длинные — выборочно по всей длительности. Совпадений может не быть. Выбранные фрагменты отправляются настроенному сервису AI.",
  "Choose 1–5 references, add your own footage, then review an editable plan. Reference footage never enters your final cut.": "Выберите 1–5 референсов, добавьте свой материал и проверьте редактируемый план. Чужие кадры не попадут в итоговое видео.",
  "Choose a decision": "Выберите решение",
  "Choose a file": "Выбрать файл",
  "Choose a file to upload.": "Выберите файл для загрузки.",
  "Choose a guide": "Выбрать руководство",
  "Choose a language and an AI voice. Create a separate version of the rendered Master; your original video stays available.": "Выберите язык и AI-голос. Создайте отдельную озвученную версию готового основного видео; оригинал останется доступен.",
  "Choose a video smaller than 250 MB.": "Выберите видео размером меньше 250 МБ.",
  "Choose a video up to 7 minutes long.": "Выберите видео длительностью до 7 минут.",
  "Choose a visually relevant sampled moment for this scene and its narration. Preserve original speech. If none fits, propose no replacement.": "Выберите подходящий фрагмент для этой сцены и речи. Сохраните исходную речь. Если ничего не подходит, не предлагайте замену.",
  "Choose different reference videos.": "Выберите разные видеореференсы.",
  "Choose examples with useful pacing, structure and visual storytelling.": "Выбирайте примеры с подходящими темпом, структурой и визуальной подачей.",
  "Choose footage": "Выбрать материал",
  "Choose from my uploaded tracks": "Выбрать из загруженных композиций",
  "Choose the changes that serve this story. Expand any recommendation to see the evidence.": "Выберите изменения, полезные для этой истории. Раскройте рекомендацию, чтобы увидеть обоснование.",
  "Choose the editing decision you want to change first.": "Сначала выберите монтажное решение, которое хотите изменить.",
  "Choose up to five references.": "Выберите до пяти референсов.",
  "Choose up to three licensed tracks. AI measures track-wide rises, drops and quiet sections, listens to selected samples, and maps its proposal to your approved scene order and creator profile. It proposes music and a volume curve; your current edit stays unchanged until you apply it. Reserves up to $0.50 within the project budget.": "Выберите до трёх лицензированных композиций. AI анализирует подъёмы, спады и тихие участки, слушает фрагменты и учитывает утверждённый порядок сцен и профиль автора. Предлагает музыку и кривую громкости; монтаж изменится только после применения. Резервирует до $0,50 из бюджета проекта.",
  "Choose your own video in step 2 to continue.": "Для продолжения выберите своё видео на шаге 2.",
  "Choose your video to upload": "Выберите видео для загрузки",
  "Circle mask": "Круговая маска",
  "Citizenship abroad": "Гражданство за рубежом",
  "Clarity": "Ясность",
  "Clean": "Минималистичный",
  "Clear": "Очистить",
  "Click": "Щелчок",
  "Clip": "Клип",
  "Clip draft preview": "Предпросмотр черновика клипа",
  "Close": "Закрыть",
  "Close-up": "Крупный план",
  "Closing CTA (seconds; 0 = off)": "Финальный призыв (секунды; 0 — выключен)",
  "Color": "Цвет",
  "Compare imported candidates with AI (up to 3)": "Сравнить импортированные материалы с AI (до 3)",
  "Compare → evidence → conclusion": "Сравнение → аргументы → вывод",
  "Compared with the previous render": "В сравнении с предыдущим рендером",
  "Comparison card": "Карточка сравнения",
  "Comparison value / label": "Значение / подпись для сравнения",
  "Comparison → conclusion": "Сравнение → вывод",
  "Completed successfully": "Успешно завершено",
  "Configured": "Настроено",
  "Confirm permission to enable upload.": "Подтвердите разрешение, чтобы загрузить файл.",
  "Confirmed saved on server": "Сохранение на сервере подтверждено",
  "Content language": "Язык контента",
  "Continue": "Продолжить",
  "Continue with Google": "Войти через Google",
  "Correct the validation errors above before saving or rendering.": "Исправьте ошибки выше перед сохранением или рендером.",
  "Could not analyze this track. Your edit is unchanged.": "Не удалось проанализировать композицию. Монтаж не изменён.",
  "Could not apply this action. Save or refresh the plan, unlock the decision and wait for running jobs.": "Не удалось выполнить действие. Сохраните или обновите план, разблокируйте решение и дождитесь завершения задач.",
  "Could not build this plan. Your saved edit is preserved.": "Не удалось построить план. Сохранённый монтаж не изменён.",
  "Could not import. Search again or check the 20-asset library limit.": "Не удалось импортировать. Повторите поиск или проверьте лимит медиатеки: 20 материалов.",
  "Could not load alternatives.": "Не удалось загрузить варианты.",
  "Could not load creative plans.": "Не удалось загрузить творческие планы.",
  "Could not load manual edits.": "Не удалось загрузить ручной монтаж.",
  "Could not load platform versions.": "Не удалось загрузить версии для платформ.",
  "Could not load this version.": "Не удалось загрузить эту версию.",
  "Could not proceed. Save your changes and wait for any running job to finish.": "Не удалось продолжить. Сохраните изменения и дождитесь завершения текущих задач.",
  "Could not refresh voiceover status. Reconnecting…": "Не удалось обновить статус озвучки. Переподключение…",
  "Could not save this change.": "Не удалось сохранить изменение.",
  "Could not start. Refresh the project and check its remaining budget.": "Не удалось запустить. Обновите проект и проверьте остаток бюджета.",
  "Cover": "Обложка",
  "Cover frame · output second": "Кадр обложки · секунда готового видео",
  "Create & review": "Создать и проверить",
  "Create a translated voiceover": "Создать озвучку на другом языке",
  "Create account": "Создать аккаунт",
  "Create another cut": "Создать ещё одну версию",
  "Create dubbed version": "Создать озвученную версию",
  "Create five editorial versions from your reviewed master, with individual titles, covers, post copy and subtitle files. Review each result before publishing.": "Создайте пять версий проверенного основного видео с отдельными заголовками, обложками, описаниями и файлами субтитров. Проверьте каждый результат перед публикацией.",
  "Create improved cut": "Создать улучшенную версию",
  "Create your first project": "Создать первый проект",
  "Created from an earlier Master. It is still available to play and download.": "Создано из предыдущей основной версии. Видео по-прежнему можно смотреть и скачивать.",
  "Creating": "Создание",
  "Creating your scene-by-scene plan…": "Создание покадрового плана…",
  "Creative brief": "Творческий бриф",
  "Creative direction (optional)": "Творческое направление (необязательно)",
  "Creative plan ready to review": "Творческий план готов к проверке",
  "Creator profile": "Профиль автора",
  "Criterion": "Критерий",
  "Crop horizontal (0–1)": "Кадрирование по горизонтали (0–1)",
  "Crop vertical (0–1)": "Кадрирование по вертикали (0–1)",
  "Cross dissolve": "Плавное наложение",
  "Current": "Текущий",
  "Current limits": "Текущие лимиты",
  "Current package": "Текущий пакет",
  "Customize": "Настроить",
  "Cut": "Склейка",
  "Daily Douyin request limit reached.": "Достигнут дневной лимит запросов Douyin.",
  "Daily search/import limit reached. Try again later.": "Достигнут дневной лимит поиска и импорта. Попробуйте позже.",
  "Data cards": "Карточки с данными",
  "Date / stage": "Дата / этап",
  "Decision": "Решение",
  "Decisions will appear after analysis finishes.": "Решения появятся после завершения анализа.",
  "Delete": "Удалить",
  "Delete project": "Удалить проект",
  "Delete this project and its videos? This cannot be undone.": "Удалить проект и его видео? Это действие нельзя отменить.",
  "Describe the product, audience, main message and claims to avoid. Lumen uses this to judge what belongs in your video.": "Опишите продукт, аудиторию, главную мысль и недопустимые утверждения. Lumen использует это при оценке уместности материалов.",
  "Describe what should change using at least 3 characters.": "Опишите желаемое изменение: не менее 3 символов.",
  "Describe what should improve. AI proposes one replacement; your current plan and finished videos stay unchanged until you apply and render it. This does not generate new footage. Reserves up to $0.50 within the project budget.": "Опишите, что улучшить. AI предложит одну замену; план и готовые видео изменятся только после применения и рендера. Новые кадры не генерируются. Резервирует до $0,50 из бюджета проекта.",
  "Description": "Описание",
  "Dimensions": "Размер кадра",
  "Director Timeline": "Монтажный таймлайн",
  "Discard unsaved changes?": "Отменить несохранённые изменения?",
  "Discard unsaved manual edits?": "Отменить несохранённые правки ручного монтажа?",
  "Dismiss": "Скрыть",
  "Document": "Документ",
  "Douyin search is not configured yet.": "Поиск Douyin ещё не настроен.",
  "Douyin search is not configured.": "Поиск Douyin не настроен.",
  "Douyin search is temporarily unavailable. Please retry.": "Поиск Douyin временно недоступен. Повторите попытку.",
  "Download MP4": "Скачать MP4",
  "Download dubbed video": "Скачать видео с озвучкой",
  "Download full package (ZIP)": "Скачать весь пакет (ZIP)",
  "Download master": "Скачать основное видео",
  "Download original": "Скачать оригинал",
  "Download source credits — also included in ZIP": "Скачать сведения об источниках — также включены в ZIP",
  "Download translated subtitles": "Скачать переведённые субтитры",
  "Download video": "Скачать видео",
  "Downloading from Douyin": "Загрузка из Douyin",
  "Draft preview approximates crop and text. Sound is original. Render the manual cut to inspect exact subtitles, audio and all transitions.": "Черновой просмотр приблизительно показывает кадрирование и текст. Звук остаётся исходным. Выполните рендер ручного монтажа, чтобы проверить точные субтитры, звук и переходы.",
  "Drafting was skipped because decisions are locked or the plan changed. Review suggestions remain available.": "Черновик не создан: решения закреплены или план изменился. Рекомендации проверки остаются доступны.",
  "Drop your footage here": "Перетащите видео сюда",
  "Duration": "Длительность",
  "Dynamic · aim for 1.5–4 s shots": "Динамичный · кадры по 1,5–4 с",
  "EN": "RU",
  "Edge smoothing": "Сглаживание границ",
  "Editing decisions from your Video DNA": "Монтажные решения на основе референсов",
  "Editing style": "Стиль монтажа",
  "Editorial assessment": "Редакторская оценка",
  "Email address": "Электронная почта",
  "Email or password is incorrect.": "Неверная почта или пароль.",
  "Emotion": "Эмоция",
  "End (s)": "Конец (с)",
  "End horizontal position": "Конечная позиция по горизонтали",
  "End vertical position": "Конечная позиция по вертикали",
  "End zoom": "Конечное приближение",
  "English": "Английский",
  "English narration and captions": "Озвучка и субтитры на английском",
  "Enter 2–5 events in chronological order. Spacing is equal, not proportional to time. Include dates and source evidence.": "Введите 2–5 событий в хронологическом порядке. Расстояния равные и не отражают течение времени. Укажите даты и источники.",
  "Enter a valid start and end time first.": "Сначала укажите корректное время начала и конца.",
  "Enter verified coordinates. The map shows approximate world locations, not property boundaries.": "Укажите проверенные координаты. Карта показывает приблизительное расположение, а не границы участков.",
  "Estimated accent": "Предполагаемый акцент",
  "Event": "Событие",
  "Evidence in your footage": "Подтверждение в вашем видео",
  "Excluded or outside shortlist": "Исключено или вне списка кандидатов",
  "Existing subtitles inside the original picture cannot be removed here.": "Субтитры, встроенные в исходное изображение, здесь удалить нельзя.",
  "Explore analysis": "Посмотреть анализ",
  "Export frame": "Экспорт кадра",
  "Export only · nothing is published automatically. Existing master captions and voice are preserved; this does not generate a new voice.": "Только экспорт — автоматической публикации нет. Субтитры и голос основного видео сохраняются; новая озвучка не создаётся.",
  "External search is unavailable. Your library is unchanged.": "Внешний поиск недоступен. Медиатека не изменена.",
  "FROM FOOTAGE TO FINISHED": "ОТ ИСХОДНИКА ДО ГОТОВОГО ВИДЕО",
  "Fade": "Затухание",
  "Fade in (seconds)": "Нарастание (секунды)",
  "Fade in / out": "Появление / затухание",
  "Fade out (seconds)": "Затухание (секунды)",
  "Fade through black": "Переход через чёрный",
  "Failed": "Ошибка",
  "Failed — action needed": "Ошибка — требуется действие",
  "Failed. Timeline preserved; no automatic retry.": "Ошибка. Таймлайн сохранён; автоматического повтора нет.",
  "File integrity, duration and audio-track checks passed.": "Проверены целостность файла, длительность и звуковая дорожка.",
  "Find a suitable moment with AI": "Найти подходящий момент с AI",
  "Find a video. Make it better.": "Найдите видео. Сделайте его лучше.",
  "Find external B-roll · Wikimedia Commons": "Найти внешние кадры · Wikimedia Commons",
  "Find references → add your footage → review the plan → render → export.": "Найдите референсы → добавьте своё видео → проверьте план → выполните рендер → экспортируйте.",
  "Find safe beat edits": "Найти безопасные склейки под ритм",
  "Find the story worth watching.": "Найдите историю, которую стоит посмотреть.",
  "Find your references": "Найдите референсы",
  "First 80 repeats shown": "Показаны первые 80 повторов",
  "First choose a decision above, then describe how it should change. This updates one decision, not the whole video.": "Сначала выберите решение выше, затем опишите изменение. Обновится одно решение, а не всё видео.",
  "Fix proposed": "Предложено исправление",
  "Footage samples supplied to AI": "Фрагменты видео, переданные AI",
  "Footage starts at (asset seconds)": "Начало материала (секунды файла)",
  "Footage starts at (source seconds)": "Начало материала (секунды исходника)",
  "For example: Bangkok skyline": "Например: панорама Бангкока",
  "For example: calm, factual, personal": "Например: спокойно, по фактам, от первого лица",
  "For example: make the opening stronger and the product easier to understand.": "Например: усилить начало и понятнее показать продукт.",
  "For example: open with the strongest moment, tighten the middle, use subtle push-ins and clear captions.": "Например: начать с сильнейшего момента, сократить середину, добавить плавные приближения и ясные субтитры.",
  "Full version reserves up to": "Полная версия резервирует до",
  "Full video guide": "Полное видеоруководство",
  "Style match": "Подгонка стиля",
  "GPU processing": "Обработка на GPU",
  "Generate full Director Timeline": "Создать полный монтажный таймлайн",
  "Generate illustrative B-roll": "Создать иллюстративную перебивку",
  "Generate up to two short clips from source-frame references. Uses your project budget.": "Создаёт до двух коротких клипов по кадрам исходника. Использует бюджет проекта.",
  "Generated footage is disabled for this project.": "Генерация кадров отключена для этого проекта.",
  "Generating voice": "Создание озвучки",
  "Generating…": "Генерация…",
  "Generation failed; original plan preserved.": "Генерация не удалась; исходный план сохранён.",
  "Generation is taking longer than expected. A saved provider job will be checked when you create the cut again.": "Генерация занимает больше времени, чем ожидалось. Сохранённая задача сервиса будет проверена при повторном создании монтажа.",
  "Google sign-in is being configured. Please check back shortly.": "Вход через Google настраивается. Попробуйте немного позже.",
  "Graphic insert": "Графическая вставка",
  "Grow from zero": "Рост от нуля",
  "Guide chapters": "Главы руководства",
  "Hashtags (up to 8)": "Хештеги (до 8)",
  "Have an invitation? Create an account": "Есть приглашение? Создать аккаунт",
  "Heading": "Заголовок",
  "Highlight words (comma-separated, up to 8)": "Выделяемые слова (через запятую, до 8)",
  "Hook": "Зацепка",
  "Hook → evidence → takeaway": "Зацепка → аргументы → вывод",
  "How the analysis was used": "Как использован анализ",
  "I have permission to use this footage.": "У меня есть разрешение на использование этого видео.",
  "I own or have permission to edit this footage.": "Видео принадлежит мне или у меня есть разрешение на его редактирование.",
  "I reviewed the source terms for this edit.": "Я проверил условия использования источника для этого монтажа.",
  "I reviewed this master and approve creating platform previews.": "Я проверил основное видео и разрешаю создать версии для платформ.",
  "Illustrative footage": "Иллюстративные кадры",
  "Import & analyze": "Импортировать и проанализировать",
  "Import could not finish. Your saved edit is unchanged. Retry or search for another clip.": "Импорт не завершён. Сохранённый монтаж не изменён. Повторите попытку или найдите другой клип.",
  "Import failed; saved edit preserved": "Ошибка импорта; сохранённый монтаж не изменён",
  "Import for preview": "Импортировать для просмотра",
  "Importing": "Импорт",
  "Importing footage…": "Импорт видео…",
  "Importing…": "Импорт…",
  "Improve current mix — keep track and alignment": "Улучшить микс — сохранить композицию и синхронизацию",
  "Improve this clip": "Улучшить этот клип",
  "Improve this video": "Улучшить это видео",
  "In your footage": "В вашем видео",
  "Included in this proposed edit": "Включено в предложенный монтаж",
  "Includes reservations for any unconfirmed provider charges.": "Включает резервы по неподтверждённым списаниям сервиса.",
  "Information density": "Плотность информации",
  "Initial version duration limits": "Ограничения длительности первых версий",
  "Insert ends at (clip seconds)": "Конец вставки (секунды клипа)",
  "Insert starts at (clip seconds)": "Начало вставки (секунды клипа)",
  "Inspect": "Проверить",
  "Keep master order": "Сохранить порядок основного видео",
  "Keep original": "Сохранить оригинал",
  "Keeps the saved track and start point. AI may adjust volume, fades and ducking; review before applying.": "Сохраняет выбранную композицию и начало. AI может настроить громкость, затухания и приглушение под речь; проверьте перед применением.",
  "LATEST WORK": "ПОСЛЕДНИЕ РАБОТЫ",
  "LUMEN · VIDEO GUIDE": "LUMEN · ВИДЕОРУКОВОДСТВО",
  "Label": "Подпись",
  "Landscape · 16:9": "Горизонтальный · 16:9",
  "Language": "Язык",
  "Large": "Крупный",
  "Last 180 days": "За 180 дней",
  "Last 24 hours": "За 24 часа",
  "Last 7 days": "За 7 дней",
  "Latitude": "Широта",
  "Learn the technique. Tell your story.": "Изучайте приёмы. Рассказывайте свою историю.",
  "Level (dB)": "Уровень (дБ)",
  "Library is full: maximum 20 assets.": "Медиатека заполнена: максимум 20 материалов.",
  "License": "Лицензия",
  "Listening and planning…": "Прослушивание и планирование…",
  "Load more": "Загрузить ещё",
  "Loading editor…": "Загрузка редактора…",
  "Loading voices…": "Загрузка голосов…",
  "Loading your workspace…": "Загрузка рабочего пространства…",
  "Loading…": "Загрузка…",
  "Location map": "Карта мест",
  "Lock": "Закрепить",
  "Lock approved version": "Закрепить утверждённую версию",
  "Lock music": "Закрепить музыку",
  "Lock this decision": "Закрепить решение",
  "Locked shot": "Закреплённый кадр",
  "Locked shot preserved": "Закреплённый кадр сохранён",
  "Longitude": "Долгота",
  "Looking closely at your video": "Изучаем ваше видео",
  "Lower music automatically while original audio is active": "Автоматически приглушать музыку при наличии исходного звука",
  "Lumen": "Lumen",
  "Lumen is examining your visuals and audio, then building a specific edit plan.": "Lumen изучает изображение и звук, затем составляет конкретный план монтажа.",
  "Lumen is retrieving the selected source. Analysis starts after the download is verified.": "Lumen загружает выбранный исходник. Анализ начнётся после проверки загрузки.",
  "Lumen keeps media processing separate from the web app, so video jobs can grow independently.": "Обработка видео в Lumen отделена от веб-приложения, поэтому её можно масштабировать независимо.",
  "Lumen video guide": "Видеоруководство Lumen",
  "MP4, MOV or WebM · up to 250 MB · 7 minutes": "MP4, MOV или WebM · до 250 МБ · 7 минут",
  "Make it stronger": "Сделать сильнее",
  "Make your own cut": "Создать свой монтаж",
  "Manual editor": "Ручной редактор",
  "Markers are estimates. Listen before final approval. Alignment shifts music only; speech and video cuts stay unchanged.": "Маркеры приблизительные. Прослушайте перед утверждением. Выравнивание сдвигает только музыку; речь и видеосклейки не меняются.",
  "Master editing · five platform previews · export": "Монтаж основной версии · пять версий для платформ · экспорт",
  "Master preview": "Просмотр основного видео",
  "Master review": "Проверка основного видео",
  "Master scene boundaries (s)": "Границы сцен основного видео (с)",
  "Match B-roll from library": "Подобрать перебивку из медиатеки",
  "Maximum 20 assets per project.": "Максимум 20 материалов на проект.",
  "Maximum 250 MB.": "Максимум 250 МБ.",
  "Maximum file size is 250 MB.": "Максимальный размер файла — 250 МБ.",
  "Measured proposal (shot labels; not face recognition)": "Параметры предложения (по меткам кадров, без распознавания лиц)",
  "Media file (up to 250 MB, 7 minutes)": "Медиафайл (до 250 МБ, 7 минут)",
  "Media storage": "Хранилище медиа",
  "Media storage is full. Delete an old project or expand storage.": "Хранилище заполнено. Удалите старый проект или увеличьте объём.",
  "Medium": "Средний",
  "Medium shot": "Средний план",
  "Meet Lumen. Then learn the workflow.": "Познакомьтесь с Lumen и освойте рабочий процесс.",
  "Minimal": "Минимальный",
  "More B-roll and factual graphics": "Больше перебивок и графики с фактами",
  "Most liked": "Больше всего лайков",
  "Motion": "Движение",
  "Move down": "Переместить вниз",
  "Move earlier": "Переместить раньше",
  "Move later": "Переместить позже",
  "Move up": "Переместить вверх",
  "Music": "Музыка",
  "Music applied to the saved plan": "Музыка применена к сохранённому плану",
  "Music bed": "Музыкальная подложка",
  "Music level (dB)": "Громкость музыки (дБ)",
  "Music planning failed; your edit is preserved": "Не удалось подобрать музыку; монтаж сохранён",
  "Music points must start at 0, increase in time and stay between -40 and -6 dB.": "Точки громкости должны начинаться с 0, идти по возрастанию времени и находиться в пределах от −40 до −6 дБ.",
  "Music repeats here": "Здесь музыка повторяется",
  "Music timing is shown in Approved output until all shots are approved.": "До утверждения всех кадров время музыки показывается в режиме утверждённого результата.",
  "Music volume curve": "Кривая громкости музыки",
  "Music: dashed amber lines mark repeats; purple lines mark estimated accents.": "Музыка: жёлтый пунктир обозначает повторы, фиолетовые линии — предполагаемые акценты.",
  "Musical direction": "Музыкальное направление",
  "Narrative purpose": "Задача в истории",
  "Narrative role": "Роль в истории",
  "Needs approval": "Нужно утверждение",
  "Needs attention": "Требует внимания",
  "Needs your review": "Нужна ваша проверка",
  "New": "Новый",
  "New cut": "Новый монтаж",
  "New plan changes appear here only after rendering again.": "Новые изменения плана появятся здесь после повторного рендера.",
  "New project": "Новый проект",
  "Newest": "Сначала новые",
  "News clip": "Новостной фрагмент",
  "Next: Video DNA → Director Timeline → your approval": "Далее: анализ референсов → монтажный таймлайн → ваше утверждение",
  "Next: review this plan in the editor": "Далее: проверьте план в редакторе",
  "No added music": "Без добавленной музыки",
  "No brief provided.": "Бриф не указан.",
  "No eligible clips found. Try a broader topic or English keywords.": "Подходящих клипов не найдено. Попробуйте более широкую тему или английские ключевые слова.",
  "No eligible videos found. Try another keyword or time range.": "Подходящих видео не найдено. Попробуйте другое ключевое слово или период.",
  "No executable correction was found. Review the explanations and refine the direction.": "Исполнимых исправлений не найдено. Прочитайте объяснения и уточните пожелания.",
  "No music tracks yet. Upload a track first, then select it here for AI to review. The menu above chooses the task, not a song.": "Музыки пока нет. Загрузите композицию и выберите её для анализа AI. Меню выше выбирает задачу, а не песню.",
  "No nearby accent": "Нет близкого акцента",
  "No new saved bytes for": "Новые данные не сохранялись в течение",
  "No projects match your search.": "По вашему запросу проектов не найдено.",
  "No projects yet": "Проектов пока нет",
  "No reliable regular tempo detected": "Устойчивый регулярный темп не обнаружен",
  "No replacement found. Your edit is unchanged.": "Замена не найдена. Монтаж не изменён.",
  "No safe alignment found. The current edit stays unchanged.": "Безопасное выравнивание не найдено. Монтаж не изменён.",
  "No safe edits identified": "Безопасные правки не найдены",
  "No speech detected": "Речь не обнаружена",
  "No spoken transcript was identified.": "Расшифровка речи не найдена.",
  "No suitable accent or approved cut is available.": "Нет подходящего акцента или утверждённой склейки.",
  "No suitable track found.": "Подходящая композиция не найдена.",
  "No transcribed speech is available in this cut. Music-only footage cannot be translated.": "В этом монтаже нет расшифрованной речи. Видео только с музыкой нельзя перевести.",
  "No transcript or title for this scene. Describe the visual you need below.": "У сцены нет расшифровки или заголовка. Опишите нужное изображение ниже.",
  "No useful executable changes were identified. Your footage has not been changed.": "Полезных выполнимых изменений не найдено. Видео не изменено.",
  "No video selected. Choose a file from your device above.": "Видео не выбрано. Выберите файл на устройстве выше.",
  "Non-adjacent source or transition": "Несмежные участки исходника или переход",
  "None": "Нет",
  "Normalize overall audio loudness": "Выровнять общую громкость",
  "Not applied": "Не применено",
  "Not changed": "Без изменений",
  "Not configured": "Не настроено",
  "Not connected": "Не подключено",
  "Not enough project or workspace budget for this request.": "Недостаточно бюджета проекта или рабочего пространства для этого запроса.",
  "Number card": "Карточка с числом",
  "Off": "Выключено",
  "Off — preserve original audio": "Выключено — сохранить исходный звук",
  "On-screen title": "Заголовок в кадре",
  "One vertical video · 30 seconds–7 minutes · up to 250 MB. Use footage you own or are licensed to edit.": "Одно вертикальное видео · от 30 секунд до 7 минут · до 250 МБ. Используйте своё видео или материал с разрешением на монтаж.",
  "Only approved shots appear here, at their final output times.": "Здесь показаны только утверждённые кадры с таймкодами итогового видео.",
  "Open Director Timeline": "Открыть монтажный таймлайн",
  "Open navigation": "Открыть навигацию",
  "Open project": "Открыть проект",
  "Opening title (seconds; 0 = off)": "Вступительный заголовок (секунды; 0 — выключен)",
  "Optional volume points use final-video seconds and override the constant music level.": "Точки громкости задаются в секундах итогового видео и заменяют постоянную громкость музыки.",
  "Original": "Оригинал",
  "Original audio": "Исходный звук",
  "Original footage — no edits shown": "Исходное видео — изменения не показаны",
  "Original shot retained; any overall changes are listed above.": "Исходный кадр сохранён; общие изменения перечислены выше.",
  "Original speech continues. Choosing library footage replaces any source cutaway on this clip.": "Исходная речь продолжается. Видео из медиатеки заменит перебивку из исходника в этом клипе.",
  "Output duration": "Длительность результата",
  "Output format": "Формат результата",
  "Output language": "Язык результата",
  "Output seconds": "Секунды итогового видео",
  "Output subtitle language: ": "Язык субтитров результата: ",
  "Overview": "Обзор",
  "Owned footage · references are used for techniques only": "Ваше видео · референсы используются только для изучения приёмов",
  "Owned source": "Собственный исходник",
  "Pacing": "Темп",
  "Package created": "Пакет создан",
  "Package history": "История пакетов",
  "Password": "Пароль",
  "Pause": "Пауза",
  "Pause upload": "Приостановить загрузку",
  "Paused. Select upload again to resume.": "Приостановлено. Снова выберите загрузку, чтобы продолжить.",
  "Place": "Разместить",
  "Place in selected scene": "Разместить в выбранной сцене",
  "Placement changes your draft, resets scene approval and keeps original speech. Save and approve before rendering.": "Размещение изменит черновик и сбросит утверждение сцены, сохранив исходную речь. Сохраните и утвердите перед рендером.",
  "Planning and searching…": "Планирование и поиск…",
  "Planning reserves $0.50 per attempt, with at most one repair, within your project budget. Rendering runs sequentially.": "Планирование резервирует $0,50 за попытку с одним возможным исправлением в рамках бюджета проекта. Рендер выполняется последовательно.",
  "Platform versions": "Версии для платформ",
  "Play selected range": "Воспроизвести выбранный диапазон",
  "Playback did not start. Press Play in the video above to watch this moment.": "Воспроизведение не началось. Нажмите кнопку воспроизведения в видео выше.",
  "Please sign in again.": "Войдите снова.",
  "Please wait before trying again.": "Подождите перед повторной попыткой.",
  "Portrait · 9:16": "Вертикальный · 9:16",
  "Position": "Расположение",
  "Post copy + edit plan": "Текст публикации и план монтажа",
  "Preparing dubbed video": "Подготовка озвученного видео",
  "Preparing selected changes": "Подготовка выбранных изменений",
  "Preparing the cut": "Подготовка монтажа",
  "Preparing the video": "Подготовка видео",
  "Preparing versions": "Подготовка версий",
  "Preparing your footage": "Подготовка вашего материала",
  "Preparing your video preview…": "Подготовка предпросмотра видео…",
  "Present": "Есть",
  "Presenter": "Ведущий",
  "Presenter screen time target (%)": "Целевая доля ведущего в кадре (%)",
  "Preserve chronology": "Сохранить хронологию",
  "Preview is the source track; render to hear the proposed mix.": "Предпросмотр воспроизводит исходную композицию; для прослушивания микса нужен рендер.",
  "Preview selected B-roll (muted)": "Предпросмотр выбранной перебивки (без звука)",
  "Preview voice": "Послушать голос",
  "Previous": "Предыдущий",
  "Primary value / label": "Основное значение / подпись",
  "Private server storage": "Закрытое серверное хранилище",
  "Private workspace": "Личное рабочее пространство",
  "Problem → solution": "Проблема → решение",
  "Problem → solution → next step": "Проблема → решение → следующий шаг",
  "Processing": "Обработка",
  "Processing connections": "Подключённые сервисы",
  "Processing could not finish. Your original is safe.": "Обработка не завершена. Исходник сохранён.",
  "Processing is already running.": "Обработка уже выполняется.",
  "Processing paused": "Обработка приостановлена",
  "Processing this package… You can leave this page and return later.": "Пакет обрабатывается… Можно уйти со страницы и вернуться позже.",
  "Processing was interrupted. No automatic paid retry was made. You can try again.": "Обработка прервана. Автоматического платного повтора не было. Можно повторить вручную.",
  "Processing was interrupted. Retry analysis or create the cut again.": "Обработка прервана. Повторите анализ или создание монтажа.",
  "Product": "Продукт",
  "Product presentation": "Презентация продукта",
  "Project AI spending limit": "Лимит расходов AI проекта",
  "Project activity": "События проекта",
  "Project name": "Название проекта",
  "Project sections": "Разделы проекта",
  "Projects": "Проекты",
  "Projects, analysis and exports are visible only to your account. AI processing shares media with the configured provider. Delete a project to remove its media from this server.": "Проекты, анализ и результаты видны только вашему аккаунту. Для AI-обработки медиа передаётся настроенному сервису. Удаление проекта удалит его медиа с сервера.",
  "Proof": "Доказательство",
  "Propose a data card": "Предложить карточку с данными",
  "Proposed edit": "Предложенный монтаж",
  "Proposed fixes need rendering and another review to verify.": "Для проверки предложенных исправлений нужен рендер и повторный просмотр.",
  "Proposed improvement": "Предлагаемое улучшение",
  "Proposed timeline": "Предложенный таймлайн",
  "Publication date": "Дата публикации",
  "Quality review": "Проверка качества",
  "Queued": "В очереди",
  "Ranges refer to the reviewed master, in playback order. Use complete scene boundaries; cuts through spoken phrases are rejected.": "Диапазоны относятся к проверенному основному видео и идут в порядке воспроизведения. Используйте границы целых сцен; разрезы внутри фраз отклоняются.",
  "Ranking (largest first)": "Рейтинг (по убыванию)",
  "Read the instructions": "Прочитать инструкцию",
  "Ready for review": "Готово к проверке",
  "Ready in library": "Готово в медиатеке",
  "Ready to analyze": "Можно анализировать",
  "Ready to export": "Готово к экспорту",
  "Ready to review": "Готово к просмотру",
  "Ready to upload.": "Можно загружать.",
  "Real estate": "Недвижимость",
  "Recent projects": "Недавние проекты",
  "Recognizing speech in the finished video": "Распознавание речи в готовом видео",
  "Recommendations": "Рекомендации",
  "Recommended": "Рекомендуется",
  "Reference": "Референс",
  "Reference analysis pending": "Ожидание анализа референсов",
  "Reference selection expired. Search again and select the references.": "Выбор референсов устарел. Повторите поиск и выберите их заново.",
  "Refine or rebuild decisions": "Уточнить или пересоздать решения",
  "Reframing": "Перекадрирование",
  "Regenerate decision": "Пересоздать решение",
  "Regenerate the selected decision with AI": "Пересоздать выбранное решение с AI",
  "Relevance": "Релевантность",
  "Relevance review was unavailable. These are unranked results; check each candidate.": "Оценка релевантности недоступна. Результаты не ранжированы; проверьте каждый.",
  "Reload": "Обновить",
  "Reload saved edits": "Загрузить сохранённые правки",
  "Remaining": "Осталось",
  "Remaining project budget": "Остаток бюджета проекта",
  "Remove": "Убрать",
  "Remove clip": "Удалить клип",
  "Remove event": "Удалить событие",
  "Remove location": "Удалить место",
  "Remove point": "Удалить точку",
  "Remove range": "Удалить диапазон",
  "Remove row": "Удалить строку",
  "Remove subtitle": "Удалить субтитр",
  "Render a Master first, then create its voiceover version.": "Сначала создайте основное видео, затем его озвученную версию.",
  "Render and review a master first.": "Сначала создайте и проверьте основное видео.",
  "Render approved plan": "Рендер утверждённого плана",
  "Render manual cut": "Рендер ручного монтажа",
  "Render queued": "Рендер в очереди",
  "Rendered master — saved result": "Основное видео — сохранённый результат",
  "Rendering": "Рендер",
  "Rendering the new cut": "Рендер новой версии",
  "Rendering uses owned footage only. AI quality review reserves up to $0.50; the project limit still applies.": "Рендер использует только ваш материал. Проверка качества AI резервирует до $0,50; действует лимит проекта.",
  "Reopen review": "Открыть проверку снова",
  "Repeating music": "Повтор музыки",
  "Replace this decision": "Заменить решение",
  "Replaced — approval required": "Заменено — требуется утверждение",
  "Replaces the current editor timeline. Review and approve shots before rendering.": "Заменит текущий таймлайн редактора. Проверьте и утвердите кадры перед рендером.",
  "Responses to quality review": "Ответы на проверку качества",
  "Restore this package": "Восстановить пакет",
  "Retry analysis": "Повторить анализ",
  "Retry import": "Повторить импорт",
  "Review and approve all shots, then save first.": "Сначала проверьте, утвердите и сохраните все кадры.",
  "Review before publishing": "Проверьте перед публикацией",
  "Review before rendering": "Проверка перед рендером",
  "Review reserves up to $0.50, plus up to two $0.50 planning attempts if a revision is needed, within your project budget. New decisions require review; your finished video is preserved.": "Проверка резервирует до $0,50, а при необходимости правок — до двух попыток планирования по $0,50 в пределах бюджета проекта. Новые решения требуют проверки; готовое видео сохраняется.",
  "Review target: 75. This is not an engagement prediction.": "Целевая оценка: 75. Это не прогноз вовлечённости.",
  "Review the finished cut": "Проверьте готовый монтаж",
  "Review the finished video with AI and draft improvements if quality is low": "Проверить готовое видео с AI и предложить улучшения при низком качестве",
  "Review the finished video yourself before publishing. AI checks cannot guarantee creative quality.": "Просмотрите готовое видео сами перед публикацией. Проверка AI не гарантирует творческого качества.",
  "Reviewing quality": "Проверка качества",
  "Revision": "Редакция",
  "Rules": "Правила",
  "RunPod is not required for this release. Analysis and generated footage use model APIs; FFmpeg handles final assembly.": "Для этой версии RunPod не нужен. Анализ и генерация работают через API моделей; финальную сборку выполняет FFmpeg.",
  "SOURCE TIMELINE": "ТАЙМЛАЙН ИСХОДНИКА",
  "Sample reserves up to": "Проба голоса резервирует до",
  "Save and render this version": "Сохранить и отрендерить версию",
  "Save changes": "Сохранить изменения",
  "Save manual edits": "Сохранить ручные правки",
  "Save or reload the latest plan first.": "Сначала сохраните или загрузите актуальный план.",
  "Save plan": "Сохранить план",
  "Save plan to enable submission": "Сохраните план для отправки",
  "Save the latest edit, unlock music and wait for running work to finish.": "Сохраните последние правки, разблокируйте музыку и дождитесь завершения задач.",
  "Save the latest timeline and unlock the clip. Another job may still be running.": "Сохраните актуальный таймлайн и разблокируйте клип. Возможно, ещё выполняется другая задача.",
  "Save your changes and wait for the current task to finish.": "Сохраните изменения и дождитесь завершения текущей задачи.",
  "Save your current plan and selected music first.": "Сначала сохраните текущий план и выбранную музыку.",
  "Save your draft, unlock the scene and wait for running tasks before searching.": "Перед поиском сохраните черновик, разблокируйте сцену и дождитесь завершения задач.",
  "Save your edits to enable rendering.": "Сохраните правки для запуска рендера.",
  "Save your plan changes before requesting or applying an alternative.": "Сохраните изменения плана перед запросом или применением альтернативы.",
  "Save your plan changes to continue.": "Сохраните изменения плана для продолжения.",
  "Saved background music": "Сохранённая фоновая музыка",
  "Saved state": "Сохранённое состояние",
  "Scene": "Сцена",
  "Scene breakdown": "Разбор сцен",
  "Scenes reordered": "Порядок сцен изменён",
  "Score change": "Изменение оценки",
  "Scores cannot be compared: one review is missing, or the evaluator/rubric is different or unknown.": "Оценки несопоставимы: одна проверка отсутствует либо модель или критерии различаются или неизвестны.",
  "Script": "Сценарий",
  "Script & intended message": "Сценарий и основная мысль",
  "Script relevance": "Соответствие сценарию",
  "Search Douyin": "Поиск в Douyin",
  "Search Douyin, choose a video, and let Lumen find specific ways to improve it.": "Найдите видео в Douyin и выберите его — Lumen предложит конкретные улучшения.",
  "Search completed": "Поиск завершён",
  "Search external footage": "Поиск внешних кадров",
  "Search failed; your edit is preserved": "Ошибка поиска; монтаж сохранён",
  "Search for a concrete subject that supports this scene. Imported footage remains a candidate until you preview and place it.": "Ищите конкретный объект, подходящий для сцены. Импортированные кадры останутся кандидатами, пока вы не просмотрите и не разместите их.",
  "Search projects": "Поиск проектов",
  "Search topics, products or ideas…": "Темы, продукты или идеи…",
  "Search video descriptions, then import candidates for preview and AI matching. Results state CC BY, CC0 or public-domain terms; review each source. Clips may be old or unrelated to your specific property or event.": "Ищите по описаниям видео и импортируйте кандидатов для просмотра и подбора с AI. В результатах указаны CC BY, CC0 или общественное достояние; проверьте каждый источник. Кадры могут быть старыми или не относиться к вашему объекту или событию.",
  "Select at least one reference in step 1 and your own video in step 2.": "Выберите хотя бы один референс на шаге 1 и своё видео на шаге 2.",
  "Select at least one reference in step 1 to continue.": "Для продолжения выберите хотя бы один референс на шаге 1.",
  "Select up to 3 tracks below": "Выберите до 3 композиций ниже",
  "Selected": "Выбрано",
  "Selected moment": "Выбранный момент",
  "Selected source": "Выбранный исходник",
  "Selected timeline scene": "Выбранная сцена таймлайна",
  "Separate AI reviews can vary. A higher score is not proof of a better edit or a prediction of engagement.": "Оценки AI могут различаться. Более высокий балл не доказывает улучшение монтажа и не прогнозирует вовлечённость.",
  "Short fades at both clip edges reduce clicks. They affect the whole source mix, including speech; they do not restore a broken musical phrase. Timing is unchanged.": "Короткие затухания на краях клипа уменьшают щелчки. Затрагивают весь исходный микс, включая речь; не восстанавливают оборванную музыкальную фразу. Тайминг не меняется.",
  "Short synthesized accents mixed with the original audio. Times are relative to this clip. Listen to the render before approval.": "Короткие синтезированные акценты поверх исходного звука. Время отсчитывается от начала клипа. Прослушайте рендер перед утверждением.",
  "Short-form videos up to 7 minutes, 250 MB per upload. Three active projects per account. Source footage remains unchanged.": "Видео до 7 минут, до 250 МБ на загрузку. До трёх активных проектов на аккаунт. Исходное видео не изменяется.",
  "Shorts: square or vertical, up to 180 seconds. Shorten the selected ranges if needed.": "Shorts: квадратный или вертикальный формат, до 180 секунд. При необходимости сократите диапазоны.",
  "Shot operations": "Операции с кадрами",
  "Shot role": "Роль кадра",
  "Shot would become too short": "Кадр станет слишком коротким",
  "Shots awaiting approval": "Кадры, ожидающие утверждения",
  "Show another moment from this video while the original speech continues. Choose footage that supports the same subject. No new footage is generated.": "Покажите другой момент исходника, сохранив текущую речь. Выберите кадры по той же теме. Новые кадры не генерируются.",
  "Sign in": "Войти",
  "Sign out": "Выйти",
  "Size": "Размер",
  "Small": "Маленький",
  "Smooth repeated music edges": "Сгладить границы повторов музыки",
  "Some criteria scored lower. Check them before approving this version.": "Некоторые критерии получили меньшую оценку. Проверьте их перед утверждением версии.",
  "Some external searches were unavailable. Results may be incomplete.": "Часть внешних поисков была недоступна. Результаты могут быть неполными.",
  "Something needs attention": "Требуется внимание",
  "Something went wrong. Please retry.": "Что-то пошло не так. Повторите попытку.",
  "Sort results": "Сортировка результатов",
  "Sound": "Звук",
  "Sound accents": "Звуковые акценты",
  "Sound effects": "Звуковые эффекты",
  "Soundtrack proposal": "Предложение музыки",
  "Source": "Источник",
  "Source / date": "Источник / дата",
  "Source / license attribution": "Источник / сведения о лицензии",
  "Source B-roll": "Перебивка из исходника",
  "Source audio edge smoothing": "Сглаживание краёв исходного звука",
  "Source end (s)": "Конец в исходнике (с)",
  "Source footage": "Исходное видео",
  "Source footage removed": "Материал удалён из монтажа",
  "Source start (s)": "Начало в исходнике (с)",
  "Source trimmed": "Исходник сокращён",
  "Source-first editing": "Монтаж на основе исходника",
  "Specific recommendations, grounded in actual moments.": "Конкретные рекомендации по реальным моментам видео.",
  "Specific subject match — verify source": "Точное соответствие объекту — проверьте источник",
  "Speech timestamps overlap. Correct the transcript timing before dubbing.": "Таймкоды речи пересекаются. Исправьте время расшифровки перед озвучкой.",
  "Speech would be affected": "Будет затронута речь",
  "Square · 1:1": "Квадратный · 1:1",
  "Start (s)": "Начало (с)",
  "Start within track (seconds)": "Начало внутри композиции (секунды)",
  "Static": "Без анимации",
  "Story structure": "Структура истории",
  "Story structure per platform": "Структура для каждой платформы",
  "Straight cut": "Прямая склейка",
  "Submitting…": "Отправка…",
  "Subtitles": "Субтитры",
  "Suggest a soundtrack": "Предложить музыку",
  "Suggest alternative": "Предложить альтернативу",
  "Suggest matching B-roll": "Подобрать перебивку",
  "Suggest mix improvements": "Предложить улучшения микса",
  "Suggest shifts of up to 0.35 seconds near measured accents. Only adjacent source cuts without timed overlays can move. Speech, locked shots, source coverage and total duration are preserved. No AI charge.": "Предложить сдвиги до 0,35 секунды к найденным акцентам. Могут двигаться только соседние склейки без привязанных по времени наложений. Речь, закреплённые кадры, охват исходника и общая длительность сохраняются. Без расходов на AI.",
  "Suggest sound accents": "Предложить звуковые акценты",
  "Suggested correction": "Предлагаемое исправление",
  "Supporting footage": "Дополнительные кадры",
  "Targets guide the proposed timeline. Available footage and complete speech take priority; review the measured result before applying.": "Цели направляют построение таймлайна. Доступный материал и целостность речи важнее; проверьте параметры результата перед применением.",
  "Task": "Задача",
  "Technical checks passed, but the AI review did not complete. Inspect the cut before using it.": "Технические проверки пройдены, но проверка AI не завершена. Просмотрите монтаж перед использованием.",
  "Technique from reference DNA": "Приём из анализа референсов",
  "Text": "Текст",
  "Text overlay": "Текст поверх видео",
  "Text overlay for this clip": "Текст поверх этого клипа",
  "The AI provider could not process this request. Retry when it is available.": "Сервис AI не смог обработать запрос. Повторите, когда он станет доступен.",
  "The AI provider needs available credits. Add credits to the connected OpenRouter account, then retry.": "Недостаточно средств у сервиса AI. Пополните подключённый аккаунт OpenRouter и повторите запрос.",
  "The AI provider needs credits.": "Сервису AI требуется пополнение баланса.",
  "The AI provider rejected its configured key.": "Сервис AI отклонил настроенный ключ.",
  "The AI response stopped before the analysis was complete. Your video is saved.": "Ответ AI оборвался до завершения анализа. Видео сохранено.",
  "The AI service returned an invalid analysis. Your video is saved; uploading it again is not necessary.": "Сервис AI вернул некорректный анализ. Видео сохранено, повторная загрузка не нужна.",
  "The Master changed. Reload this panel and create a version from the latest Master.": "Основное видео изменилось. Обновите панель и создайте озвучку из последней версии.",
  "The analysis did not find a grounded change it can execute. Review the observations below.": "Анализ не нашёл обоснованных выполнимых изменений. Просмотрите наблюдения ниже.",
  "The camera moves smoothly from the initial framing above to these end values. Matching values keep the camera still.": "Камера плавно перемещается от начального кадрирования к этим конечным значениям. Одинаковые значения оставляют камеру неподвижной.",
  "The card fades over the footage. Render to check its exact appearance.": "Карточка плавно появляется поверх видео. Выполните рендер, чтобы проверить точный вид.",
  "The editable plan appears after reference and owned-footage analysis.": "Редактируемый план появится после анализа референсов и вашего видео.",
  "The entire reviewed image is preserved; padding is added when needed.": "Всё проверенное изображение сохраняется; при необходимости добавляются поля.",
  "The final render preserves the base clip audio. Review the rendered transitions before publishing.": "Финальный рендер сохраняет звук основного клипа. Проверьте переходы перед публикацией.",
  "The footage provider rejected the request. Check provider access and credits.": "Сервис генерации кадров отклонил запрос. Проверьте доступ и баланс.",
  "The invitation code is not valid.": "Неверный код приглашения.",
  "The labels below come from the executable edit, not the AI description.": "Подписи ниже взяты из исполнимого монтажа, а не из описания AI.",
  "The manual editor becomes available when analysis is complete.": "Ручной редактор станет доступен после анализа.",
  "The model returned an incomplete analysis. Your original is safe; you can retry.": "Модель вернула неполный анализ. Исходник сохранён; можно повторить попытку.",
  "The opening overlaps a deleted segment. Adjust the selection.": "Начало пересекается с удалённым фрагментом. Измените выбор.",
  "The operation failed. Try again; your source is preserved.": "Не удалось выполнить операцию. Повторите попытку; исходник сохранён.",
  "The package changed. Refresh and try again.": "Пакет изменился. Обновите страницу и повторите.",
  "The plan changed. Reload it before saving.": "План изменился. Обновите его перед сохранением.",
  "The plan changed. Reload saved edits before continuing.": "План изменился. Загрузите сохранённые правки перед продолжением.",
  "The plan changed. Request a new alternative.": "План изменился. Запросите новую альтернативу.",
  "The project changed. Generate a new plan before applying it.": "Проект изменился. Создайте новый план перед применением.",
  "The project library is full (20 assets).": "Медиатека проекта заполнена (20 материалов).",
  "The project or workspace budget is exhausted.": "Бюджет проекта или рабочего пространства исчерпан.",
  "The provider submission could not be confirmed. Automatic resubmission is paused to avoid duplicate charges.": "Отправка запроса сервису не подтверждена. Автоматический повтор остановлен, чтобы избежать двойной оплаты.",
  "The request could not be completed. Please try again.": "Не удалось выполнить запрос. Повторите попытку.",
  "This project is not available.": "Этот проект недоступен.",
  "It may have been removed, or this link does not match a project in your workspace.": "Возможно, его удалили, или ссылка не относится к проекту в этом рабочем пространстве.",
  "Back to projects": "К проектам",
  "The selected Douyin reference could not be retrieved. Your uploaded video is preserved; this is not an upload failure.": "Не удалось получить выбранный референс Douyin. Ваше загруженное видео сохранено; это не ошибка загрузки.",
  "The selected Douyin video cannot be downloaded. Try another result.": "Выбранное видео Douyin нельзя скачать. Попробуйте другое.",
  "The selected cuts remove too much footage.": "Выбранные правки удаляют слишком много материала.",
  "The selected opening overlaps a selected removal. Deselect one of these changes.": "Выбранное начало пересекается с удаляемым фрагментом. Снимите одно из этих изменений.",
  "The server needs more storage before creating another version.": "Перед созданием новой версии нужно увеличить свободное место на сервере.",
  "The source exceeds the 50 MB import limit or its download stalled. Choose another clip.": "Исходник превышает лимит импорта 50 МБ или загрузка зависла. Выберите другой клип.",
  "The source terms changed or could not be verified. Search again and review the current source.": "Условия источника изменились или не подтверждены. Повторите поиск и проверьте актуальный источник.",
  "The strongest moment": "Самый сильный момент",
  "The supporting footage could not be generated.": "Не удалось создать дополнительные кадры.",
  "The translation service returned an incomplete result. You can retry; the Master is unchanged.": "Сервис перевода вернул неполный результат. Можно повторить; основное видео не изменено.",
  "The upload response timed out. Try again to resume.": "Время ожидания ответа при загрузке истекло. Повторите для продолжения.",
  "The video could not be downloaded.": "Не удалось скачать видео.",
  "The video exceeds the 250 MB limit.": "Видео превышает лимит 250 МБ.",
  "The voice provider needs credits. Contact the workspace administrator.": "Сервису озвучки требуется пополнение. Обратитесь к администратору рабочего пространства.",
  "The workspace has insufficient storage.": "В рабочем пространстве недостаточно места.",
  "These overlays are rendered into this version. Existing master captions stay unchanged. On short cuts, the opening title takes priority over an overlapping CTA.": "Эти наложения встраиваются в данную версию. Субтитры основного видео не меняются. В коротком монтаже вступительный заголовок важнее пересекающегося с ним призыва.",
  "These results expired. Please search again.": "Эти результаты устарели. Повторите поиск.",
  "These versions belong to an older master. Generate a new package for the current master.": "Версии относятся к старому основному видео. Создайте новый пакет для текущего.",
  "This adjusts the mixed audio track, not the separate voice/music balance.": "Настраивает смешанную дорожку, а не отдельный баланс речи и музыки.",
  "This cut crosses earlier transcript timestamps. Speech will be recognized again from the finished Master before translation.": "Монтаж пересекает прежние границы расшифровки. Перед переводом речь будет заново распознана в готовом основном видео.",
  "This cut needs human review.": "Этот монтаж нужно проверить человеку.",
  "This decision is locked. Unlock and save it before requesting changes.": "Решение закреплено. Разблокируйте и сохраните его перед запросом изменений.",
  "This email already has an account.": "Для этой почты уже есть аккаунт.",
  "This file could not be read as a supported video.": "Не удалось прочитать файл как поддерживаемое видео.",
  "This is a spending ceiling, not a price quote. Reference analysis, planning and review share it; TikHub charges are separate. Footage is sent to the configured AI provider. No rendering starts before your approval.": "Это потолок расходов, а не фиксированная цена. Анализ референсов, планирование и проверка используют общий лимит; TikHub оплачивается отдельно. Видео передаётся настроенному сервису AI. Рендер не начнётся без вашего утверждения.",
  "This master belongs to an earlier plan. Review and render the updated plan to include your changes.": "Основное видео относится к предыдущему плану. Проверьте и отрендерите обновлённый план, чтобы включить изменения.",
  "This media could not be processed.": "Не удалось обработать этот медиафайл.",
  "Subtitles cannot be burned because FFmpeg has no ass filter.": "Субтитры нельзя вшить: в FFmpeg нет фильтра ass.",
  "Trends": "Тренды",
  "This project starts from a trend. The script is a new structure, not the reference video. New project clears it.": "Этот проект начинается с тренда. Сценарий — новая структура, не ролик-референс. Новый проект очищает её.",
  "All trends": "Все тренды",
  "Loading trend…": "Загрузка тренда…",
  "No caption saved.": "Подпись не сохранена.",
  "Score": "Оценка",
  "views": "просмотры",
  "The reference file stays at its URL. Lumen does not download it.": "Файл референса остаётся по ссылке. Lumen его не скачивает.",
  "Analyze": "Разобрать",
  "Generate parody": "Сделать вариации",
  "Why it works": "Почему это работает",
  "Chosen": "Выбрано",
  "Use this version": "Взять эту версию",
  "Create with Lumen": "Создать в Lumen",
  "Find a structure. Then tell your own story.": "Сначала структура. Потом своя история.",
  "Trends sit in front of Studio. You still upload your footage and approve every edit.": "Тренды стоят перед Studio. Свой ролик и каждое решение по монтажу остаются за вами.",
  "Use as reference": "Взять как референс",
  "Add a public URL": "Добавить публичную ссылку",
  "Paste a link and the numbers you can see. Lumen stores that text. It does not open the video.": "Вставьте ссылку и цифры, которые видите. Lumen сохранит этот текст и не откроет видео.",
  "URL": "Ссылка",
  "Creator": "Автор",
  "Published": "Опубликовано",
  "Duration, seconds": "Длительность, секунды",
  "Caption": "Подпись",
  "Hashtags": "Хештеги",
  "Audio or music": "Звук или музыка",
  "Views": "Просмотры",
  "Likes": "Лайки",
  "Comments": "Комментарии",
  "Shares": "Репосты",
  "Save trend": "Сохранить тренд",
  "This package belongs to an older master.": "Пакет относится к предыдущему основному видео.",
  "This plan preserves the original. It contains no executable improvements. Refine the direction to request a different edit.": "План сохраняет оригинал и не содержит выполнимых улучшений. Уточните пожелания, чтобы запросить другой монтаж.",
  "This project or workspace reached its AI spending limit.": "Достигнут лимит расходов AI проекта или рабочего пространства.",
  "This search belongs to an older saved edit. Run it again for the current scene.": "Поиск относится к предыдущему сохранённому монтажу. Повторите для текущей сцены.",
  "This temporary upload expired. Select the file again to start a new upload.": "Временная загрузка устарела. Выберите файл заново и начните новую загрузку.",
  "This transcript is too long for one voiceover job. Use a shorter cut.": "Расшифровка слишком длинная для одной задачи озвучки. Используйте более короткий монтаж.",
  "This version replaces all original audio, including mixed music and background sounds. It does not clone the speaker or change lip movements. Existing text inside the picture stays unchanged.": "Эта версия заменяет весь исходный звук, включая музыку и фоновые шумы. Голос человека не клонируется, движения губ не меняются. Встроенный текст в кадре остаётся прежним.",
  "Three projects are already processing. Wait for one to finish.": "Уже обрабатываются три проекта. Дождитесь завершения одного из них.",
  "TikHub account needs credits.": "Аккаунт TikHub требует пополнения.",
  "TikHub authentication failed. The service configuration needs attention.": "Ошибка авторизации TikHub. Нужно проверить настройки сервиса.",
  "TikHub could not retrieve the selected Douyin reference. Your uploaded video is preserved. Retrying may fail again while the reference is unavailable.": "TikHub не смог получить выбранный референс Douyin. Ваше видео сохранено. Пока референс недоступен, повторная попытка тоже может завершиться ошибкой.",
  "TikHub could not retrieve this video. Please retry.": "TikHub не смог получить видео. Повторите попытку.",
  "TikHub is rate limiting requests. Please try later.": "TikHub ограничивает частоту запросов. Попробуйте позже.",
  "TikHub is rate-limiting requests. Please retry later.": "TikHub ограничивает частоту запросов. Повторите позже.",
  "TikHub needs account credits.": "Нужно пополнить баланс TikHub.",
  "TikHub rejected its configured key.": "TikHub отклонил настроенный ключ.",
  "TikHub requires credits to retrieve the reference.": "Для получения референса нужно пополнить TikHub.",
  "Time (s)": "Время (с)",
  "Timed overlays or effects": "Наложения или эффекты с привязкой ко времени",
  "Timeline of events": "Хронология событий",
  "Timeline view": "Вид таймлайна",
  "Times refer to the original footage. Repeated ranges repeat that footage; omitted ranges are cut. Check that cuts preserve complete speech.": "Таймкоды относятся к исходнику. Повторённые диапазоны повторяют материал, пропущенные — вырезаются. Проверьте целостность речи на склейках.",
  "Title position": "Расположение заголовка",
  "Title style": "Стиль заголовка",
  "To customize captions, render a new master and create a new platform package. This older master has embedded captions.": "Чтобы настроить субтитры, отрендерите новое основное видео и создайте новый пакет. В этой старой версии субтитры встроены в изображение.",
  "Tone": "Тон",
  "Too many requests. Please try again shortly.": "Слишком много запросов. Попробуйте чуть позже.",
  "Too many requests. Please wait a few minutes.": "Слишком много запросов. Подождите несколько минут.",
  "Too many unfinished uploads. Resume an existing upload or try again later.": "Слишком много незавершённых загрузок. Продолжите существующую или попробуйте позже.",
  "Top": "Сверху",
  "Topic": "Тема",
  "Track": "Композиция",
  "Transcript": "Расшифровка",
  "Transition": "Переход",
  "Translating speech": "Перевод речи",
  "Travel": "Путешествия",
  "Try another editing decision": "Попробовать другое монтажное решение",
  "Understand": "Понять",
  "Understand what works. See exactly what to improve. Turn your footage into a considered, compelling cut.": "Узнайте, что работает и что улучшить. Превратите исходник в продуманный, увлекательный монтаж.",
  "Understanding visuals & audio": "Анализ изображения и звука",
  "Unlock": "Разблокировать",
  "Unlock and save first before changing a locked decision.": "Перед изменением закреплённого решения разблокируйте и сохраните его.",
  "Unlock music": "Разблокировать музыку",
  "Unlock saved timeline decisions before replacing the whole edit.": "Разблокируйте сохранённые решения таймлайна перед заменой всего монтажа.",
  "Unlock this version first.": "Сначала разблокируйте эту версию.",
  "Unsaved changes": "Несохранённые изменения",
  "Unsaved manual edits": "Несохранённые ручные правки",
  "Untitled card": "Карточка без названия",
  "Upload a licensed track in the library above. Music repeats to match the approved edit. Save the plan and render to hear the mix.": "Загрузите лицензированную композицию в медиатеку выше. Музыка повторяется до конца утверждённого монтажа. Сохраните план и выполните рендер, чтобы услышать микс.",
  "Upload a video": "Загрузить видео",
  "Upload connection interrupted. Keep this page open and try again to resume from the last saved chunk.": "Соединение при загрузке прервано. Оставьте страницу открытой и повторите, чтобы продолжить с последнего сохранённого фрагмента.",
  "Upload could not finish. Check the media file and retry; saved chunks can resume.": "Загрузка не завершена. Проверьте файл и повторите; сохранённые фрагменты можно дозагрузить.",
  "Upload failed": "Ошибка загрузки",
  "Upload failed. Please check your connection and try again.": "Загрузка не удалась. Проверьте соединение и повторите.",
  "Upload footage to the B-roll media library first.": "Сначала загрузите видео в медиатеку перебивок.",
  "Upload music": "Загрузить музыку",
  "Upload paused": "Загрузка приостановлена",
  "Upload paused — saved chunks are preserved. Start again to resume.": "Загрузка приостановлена — полученные фрагменты сохранены. Запустите снова для продолжения.",
  "Upload received · checking video": "Загрузка получена · проверка видео",
  "Upload received. Checking the file…": "Загрузка получена. Проверка файла…",
  "Upload server temporarily unavailable. Try again to resume.": "Сервер загрузки временно недоступен. Повторите для продолжения.",
  "Upload timed out. Try again to resume; completed chunks are saved for 24 hours.": "Время загрузки истекло. Повторите для продолжения; готовые фрагменты хранятся 24 часа.",
  "Upload to library": "Загрузить в медиатеку",
  "Upload video or music you own or are licensed to use. Add video to a clip or choose a music track below. Uploading does not change your edit.": "Загружайте свои видео и музыку или материалы с лицензией. Добавьте видео в клип или выберите музыку ниже. Загрузка не меняет монтаж.",
  "Upload your first video to start building your creative library.": "Загрузите первое видео, чтобы начать собирать медиатеку.",
  "Uploaded successfully — ready to use": "Загружено — можно использовать",
  "Uploading": "Загрузка",
  "Uploading video": "Загрузка видео",
  "Uploading · saved": "Загрузка · сохранено",
  "Use Master preview to see the rendered changes.": "Переключитесь на основное видео, чтобы увидеть готовые изменения.",
  "Use Preview voice or Create dubbed version to retry with the selected voice.": "Для повтора с выбранным голосом нажмите «Послушать голос» или «Создать озвученную версию».",
  "Use a vertical video for this pilot.": "Для этой пробной версии используйте вертикальное видео.",
  "Use as opening": "Использовать в начале",
  "Use master settings": "Использовать настройки основного видео",
  "Use media between 0.1 and 420 seconds.": "Используйте материалы длительностью от 0,1 до 420 секунд.",
  "Use one metric and the same unit for every value. Enter the unit in the primary label. Rankings sort largest first; values are not fact-checked.": "Используйте один показатель и одинаковые единицы для всех значений. Укажите единицу в основной подписи. Рейтинг сортируется по убыванию; факты не проверяются.",
  "Use owned footage between 30 seconds and 7 minutes.": "Используйте своё видео длительностью от 30 секунд до 7 минут.",
  "Use recommended changes": "Применить рекомендуемые изменения",
  "Use scene boundaries and complete speech ranges; check the content language and overlapping ranges.": "Используйте границы сцен и целые фразы; проверьте язык контента и пересечения диапазонов.",
  "Use this plan → Review shots": "Применить план → Проверить кадры",
  "Use verified figures and identify their source. Times are relative to this clip. Both language versions are required; rendering follows the project language.": "Используйте проверенные данные и укажите источник. Время отсчитывается от начала клипа. Нужны обе языковые версии; рендер использует язык проекта.",
  "Uses the selected shot and its script context. The result is synthetic illustration, not news evidence or verified footage of a property. Preview and approve before rendering.": "Использует выбранный кадр и контекст сценария. Результат — синтетическая иллюстрация, а не новостное доказательство или проверенное видео объекта. Просмотрите и утвердите перед рендером.",
  "Uses your footage and cached reference analysis. Reserves $0.50 per attempt, with at most one repair, within your project budget. Locked shots and their global audio/caption settings are preserved. External footage and new music are not generated.": "Использует ваше видео и сохранённый анализ референсов. Резервирует $0,50 за попытку с одним возможным исправлением в рамках бюджета. Закреплённые кадры и общие настройки звука и субтитров сохраняются. Внешние кадры и новая музыка не создаются.",
  "Value": "Значение",
  "Version creation failed. Your master is preserved. Check remaining budget before retrying.": "Не удалось создать версии. Основное видео сохранено. Проверьте остаток бюджета перед повтором.",
  "Video": "Видео",
  "Video & music library": "Медиатека видео и музыки",
  "Video / B-roll": "Видео / перебивка",
  "Video created — review required": "Видео создано — требуется проверка",
  "Video format": "Формат видео",
  "Video guide": "Видеоруководство",
  "Video intelligence and thoughtful editing, in one workspace.": "Анализ видео и продуманный монтаж в одном рабочем пространстве.",
  "Video rendering": "Рендер видео",
  "Video results up to 7 minutes · Chinese keywords work best for Douyin.": "Видео до 7 минут · для Douyin лучше подходят китайские ключевые слова.",
  "Video studio": "Видеостудия",
  "Video understanding": "Анализ видео",
  "View all projects": "Все проекты",
  "View moment": "Посмотреть момент",
  "View on Douyin": "Открыть в Douyin",
  "View source and rights": "Посмотреть источник и права",
  "Viewing a saved package. Downloads include that version's review state.": "Открыт сохранённый пакет. Скачиваемые файлы содержат статус проверки этой версии.",
  "Visual": "Изображение",
  "Visual insert: cards, charts and rankings": "Графические вставки: карточки, диаграммы и рейтинги",
  "Visual subject": "Объект в кадре",
  "Visual support": "Визуальное сопровождение",
  "Visuals": "Визуальная часть",
  "Voice & style": "Голос и стиль",
  "Voice generation is not configured on this server yet.": "Генерация озвучки на этом сервере ещё не настроена.",
  "Voice sample": "Проба голоса",
  "Voiceover could not finish. Your Master and previous versions are safe. Please try again.": "Озвучка не завершена. Основное видео и предыдущие версии сохранены. Повторите попытку.",
  "Voiceover language": "Язык озвучки",
  "Wait for the current project task to finish.": "Дождитесь завершения текущей задачи проекта.",
  "Wait for the current task to finish.": "Дождитесь завершения текущей задачи.",
  "Waiting for a worker": "Ожидание обработчика",
  "Waiting for server confirmation": "Ожидание подтверждения сервера",
  "Watch this moment": "Посмотреть этот момент",
  "What Lumen noticed": "Что заметил Lumen",
  "What needs your judgment": "Что требует вашего решения",
  "What should AI do?": "Что должен сделать AI?",
  "What should change?": "Что изменить?",
  "What should improve?": "Что улучшить?",
  "What should the viewer understand or do? Include your script and facts that must stay unchanged.": "Что зритель должен понять или сделать? Добавьте сценарий и факты, которые нельзя менять.",
  "What should this video achieve?": "Какова цель этого видео?",
  "White": "Белый",
  "Who is this for?": "Для кого это видео?",
  "Whoosh": "Свист пролёта",
  "Why other cuts stayed unchanged": "Почему другие склейки не изменились",
  "Why this helps": "Почему это поможет",
  "Why this reference technique fits": "Почему подходит приём из референса",
  "Wipe left": "Сдвиг влево",
  "Workspace": "Рабочее пространство",
  "Workspace invitation code": "Код приглашения",
  "Yellow": "Жёлтый",
  "You already have three active projects. Wait for one to finish.": "У вас уже три активных проекта. Дождитесь завершения одного из них.",
  "You already have three videos processing.": "Уже обрабатываются три ваших видео.",
  "You can browse decisions while generation runs. Wait for it to finish before requesting another change.": "Во время генерации можно просматривать решения. Дождитесь завершения перед запросом следующего изменения.",
  "You can pause and resume without losing saved chunks.": "Можно приостановить и продолжить без потери сохранённых фрагментов.",
  "Your analysis is ready": "Анализ готов",
  "Your creative workspace, connected and ready.": "Ваше творческое рабочее пространство настроено и готово.",
  "Your edit plan": "План монтажа",
  "Your footage leads. Every suggested change has a reason.": "В основе — ваше видео. У каждого предложенного изменения есть причина.",
  "Your new cut is queued": "Новый монтаж поставлен в очередь",
  "Your new cut is ready": "Новый монтаж готов",
  "Your next great video\nstarts with a better look.": "Хорошее видео начинается с внимательного взгляда.",
  "Your projects": "Ваши проекты",
  "Your session expired. Sign in again.": "Сессия истекла. Войдите снова.",
  "Your source is saved. This page updates automatically.": "Исходник сохранён. Страница обновляется автоматически.",
  "Your video is safely saved. Processing starts when a worker is available.": "Видео сохранено. Обработка начнётся, когда освободится обработчик.",
  "Your video stays private to your account. AI analysis sends it to our configured model provider.": "Видео доступно только вашему аккаунту. Для анализа оно отправляется настроенному сервису AI.",
  "Zoom (1–3×)": "Приближение (1–3×)",
  "Zoom transition": "Zoom-переход",
  "approved": "утверждено",
  "changes applied": "изменений применено",
  "confidence": "уверенность",
  "detected accents": "найдено акцентов",
  "dubbed version": "озвученная версия",
  "e.g. Introduce our ceramic pour-over set to home coffee enthusiasts. Show how easy it is to use. Keep the original product and avoid unsupported claims.": "Например: познакомить любителей домашнего кофе с нашим керамическим набором для заваривания. Показать простоту использования. Сохранить реальный продукт и избегать неподтверждённых заявлений.",
  "estimated BPM": "примерный BPM",
  "external footage": "внешние кадры",
  "generated clips": "созданных клипов",
  "insert": "вставка",
  "sec": "с",
  "shots": "кадров",
  "source": "исходник",
  "versions approved": "версий утверждено",
  "videos": "видео",
  "Interface language": "Язык интерфейса",
  "This Google account does not have access. Choose an approved account.": "У этого аккаунта Google нет доступа. Выберите разрешённый аккаунт.",
  "Google sign-in could not be completed. Please try again.": "Не удалось войти через Google. Повторите попытку.",
  "English step-by-step Lumen guide": "Пошаговое руководство Lumen на английском",
  "English Lumen overview": "Обзор Lumen на английском",
  "Lumen Workspace": "Рабочее пространство Lumen",
  "WORKSPACE": "РАБОЧЕЕ ПРОСТРАНСТВО",
  "VIDEO INTELLIGENCE STUDIO": "СТУДИЯ АНАЛИЗА ВИДЕО",
  "01 — SEE THE POSSIBILITIES": "01 — ОТКРОЙТЕ ВОЗМОЖНОСТИ",
  "LUMEN WORKSPACE": "РАБОЧЕЕ ПРОСТРАНСТВО LUMEN",
  "LUMEN VIDEO STUDIO": "ВИДЕОСТУДИЯ LUMEN",
  "LUMEN / VIDEO INTELLIGENCE": "LUMEN / АНАЛИЗ ВИДЕО",
  "LUMEN LIBRARY": "МЕДИАТЕКА LUMEN",
  "A NEW STORY": "НОВАЯ ИСТОРИЯ",
  "THE NEXT CUT": "НОВЫЙ МОНТАЖ",
  "THE BIG PICTURE": "ОБЩАЯ КАРТИНА",
  "LUMEN / DIRECTOR STUDIO": "LUMEN / МОНТАЖНАЯ СТУДИЯ",
  "DIRECTOR STUDIO": "МОНТАЖНАЯ СТУДИЯ",
  "Generated analysis is displayed in English.": "Текст AI-анализа показан на английском.",
  "简体中文": "Китайский (упрощённый)",
  "Retry platform versions": "Повторить создание версий",
  "Create 5 versions": "Создать 5 версий",
  "Cancel editing": "Отменить редактирование",
  "Edit this version": "Редактировать версию",
  "Video DNA": "Анализ референсов",
  "Automatic style match is off for this project.": "Для этого проекта автоматическое совпадение стиля выключено.",
  "Match the reference pacing and the visual effects this editor can reproduce, then render. You still approve the result and can edit every cut.": "Подогнать ритм референса и те визуальные эффекты, которые этот редактор умеет повторить, и сразу собрать ролик. Результат всё равно нужно утвердить, и каждый стык можно поправить.",
  "The owned video was cut to the reference rhythm.": "Ваше видео нарезано в ритме референса.",
  "Zoom and punch-in were applied where the reference uses them.": "Наезд поставлен там, где он есть в референсе.",
  "Cuts, fades, dissolves, wipes and circle transitions follow the reference.": "Стыки, затемнения, наплывы, вытеснения и круговые переходы следуют референсу.",
  "Owned speech was burned as captions.": "В субтитры записана ваша речь.",
  "Audio level was normalized.": "Громкость выровнена.",
  "No owned captions were added.": "Свои субтитры не добавлялись.",
  "Motion tracking is not available. A fixed zoom is used instead.": "Трекинг движения недоступен. Вместо него стоит фиксированный наезд.",
  "Presenter cutout is not available.": "Вырезание ведущего недоступно.",
  "Background replacement is not available.": "Замена фона недоступна.",
  "Speed ramps are not available.": "Плавное изменение скорости недоступно.",
  "Masks are not available.": "Маски недоступны.",
  "Split screen is not available.": "Разделённый экран недоступен.",
  "Automatic color and lighting match is not available.": "Автоматическое совпадение цвета и света недоступно.",
  "Kinetic typography is not cloned. Owned captions are used when speech exists.": "Кинетическая типографика не копируется. Если есть речь, ставятся ваши субтитры.",
  "A chart or number card needs the figure and its label from you. Nothing was invented.": "Для карточки с цифрой или графика нужны ваши число и подпись. Ничего не выдумано.",
  "Extra pictures were not added. Upload an asset if this shot needs one.": "Дополнительные картинки не добавлялись. Загрузите материал, если он нужен этому кадру.",
  "Captions need a speech transcript from your video.": "Для субтитров нужна расшифровка речи из вашего видео.",
  "Reference music was not copied.": "Музыка референса не копировалась.",
  "The automatic cut could not be built. Regenerate video to try again.": "Автоматический монтаж не собрался. Нажмите «Собрать видео заново».",
  "Automatic style match": "Автоматическое совпадение стиля",
  "Style match starts when analysis finishes.": "Совпадение стиля начнётся, когда закончится анализ.",
  "Visual fidelity to the reference structure. Unsupported effects are listed and are not imitated. The cut uses your footage only.": "Насколько монтаж совпадает со структурой референса. Недоступные эффекты перечислены и не имитируются. В ролике только ваше видео.",
  "You approved this cut.": "Вы утвердили этот ролик.",
  "Shot structure": "Структура кадров",
  "Visual pacing": "Визуальный ритм",
  "Effect similarity": "Схожесть эффектов",
  "Motion-graphic style": "Стиль графики",
  "Color treatment": "Цвет",
  "Production quality": "Готовность сборки",
  "Needs your input": "Нужны ваши данные",
  "Not reproduced": "Не повторено",
  "Approve this cut": "Утвердить этот ролик",
  "Regenerate video": "Собрать видео заново",
  "Section": "Фрагмент",
  "Style section": "Фрагмент стиля",
  "Regenerate selected section": "Собрать выбранный фрагмент заново",
  "Unusable sections that do not cut through speech were removed.": "Убраны непригодные куски, которые не режут речь.",
  "Crop, punch-in and camera moves follow the reference.": "Кадрирование, наезд и движение камеры следуют референсу.",
  "Short labels use words from your own speech.": "Короткие подписи берутся из вашей речи.",
  "Charts and number cards use figures from your script.": "Графики и карточки с цифрами берут числа из вашего сценария.",
  "A cutaway uses another moment of your own footage.": "Перебивка берётся из другого момента вашего видео.",
  "Numbers and keywords from your speech are highlighted.": "Числа и ключевые слова из вашей речи выделены.",
  "Exposure and color were lifted slightly. The reference grade was not copied.": "Экспозиция и цвет чуть усилены. Цветокор референса не копировался.",
  "Blur is not available.": "Размытие недоступно.",
  "Glow is not available.": "Свечение недоступно.",
  "Drop shadows are not available.": "Тени недоступны.",
  "Stabilization is not available.": "Стабилизация недоступна.",
  "Reference video": "Референс-видео",
  "Upload the reference video. The finished film still uses only your footage.": "Загрузите референс. В готовом ролике по-прежнему только ваше видео.",
  "Color was shifted toward the reference measurement.": "Цвет сдвинут к измерению референса.",
  "Short reference beats play with a speed change.": "Короткие кадры референса идут с изменением скорости.",
  "Blur was applied where the reference uses it.": "Размытие стоит там, где оно есть в референсе.",
  "A light glow was applied.": "Добавлено лёгкое свечение.",
  "A vignette shadow was applied.": "Добавлена виньетка.",
  "The frame was split into two panels.": "Кадр разделён на две панели.",
  "The shot was stabilized.": "Кадр стабилизирован.",
  "A flat background was separated and softened.": "Однотонный фон отделён и смягчён.",
  "The on-screen label moves across the frame.": "Подпись движется по кадру.",
  "The frame follows where the detail moves.": "Кадр следует за тем, куда смещается деталь.",
  "The presenter sits in a soft window over a clean plate.": "Ведущий в мягком окне на чистой подложке.",
  "Exposure was shifted toward the reference measurement.": "Экспозиция сдвинута к измерению референса.",
  "A progress bar follows the position in the cut.": "Полоса прогресса идёт по месту фрагмента в ролике.",
  "A title-like reference shot is replaced by a chart of your figures, fading in and out.": "Кадр-плашка из референса заменён графиком ваших цифр: он проявляется и гаснет.",
  "A lower band fades in and out over the presenter.": "Нижняя полоса проявляется и гаснет поверх ведущего.",
  "A small mark fades in and out on that band.": "Маленькая метка на этой полосе проявляется и гаснет.",
  "A title-like shot with no figures holds another frame of your footage, then lets it go.": "Кадр-плашка без цифр держит другой кадр вашего видео и потом отпускает его.",
  "A screen-like reference shot holds your frame inside a border, then lets it go.": "Кадр, похожий на экран, держит ваш кадр в рамке и потом отпускает его.",
  "An illustration of equal shapes is drawn from your words and fades out.": "Иллюстрация из одинаковых фигур строится по вашим словам и гаснет.",
  "One generated picture uses your words. It has no text from the reference.": "Одна сгенерированная картинка берёт ваши слова. Текста из референса в ней нет.",
  "The other half of a split frame is another moment of your footage.": "Вторая половина кадра — другой момент вашего видео.",
  "Face tracking is not available. The frame follows a moving bright area when one is measured.": "Лицо не отслеживается. Если яркая область движется и это измерено, кадр идёт за ней.",
  "Extra pictures were not added. Confirm a license in the stock library on this page, or upload your own.": "Дополнительные кадры не добавлены. Подтвердите лицензию в библиотеке на этой странице или загрузите своё.",
  "A Commons clip with a CC BY, CC0, or public-domain license was inserted. Its credit stays on the asset.": "Вставлен ролик Commons с лицензией CC BY, CC0 или общественным достоянием. Авторство сохранено у материала.",
  "No Commons clip with a CC BY, CC0, or public-domain license matched your words.": "По вашим словам не нашёлся ролик Commons с лицензией CC BY, CC0 или общественным достоянием."
};
