import {useEffect,useRef,useState} from 'react';
import type {Lang} from './types';
import {Star,Plus,Check,Music2,Copy} from 'lucide-react';

type Track={key:string;title:string;artist:string;origin:'curated'|'uploaded';mood:string;duration:number;bpm?:number;attribution:string;license?:string;license_url?:string;source_url?:string;favorite:boolean;available:boolean};
export function SoundtrackLibrary({pid,lang,full,onChanged}:{pid:string;lang:Lang;full:boolean;onChanged:()=>Promise<void>}){
 const t=(ru:string,en:string,zh:string)=>lang==='ru'?ru:lang==='zh'?zh:en;
 const [tracks,setTracks]=useState<Track[]>([]),[tab,setTab]=useState('curated'),[mood,setMood]=useState('all'),[query,setQuery]=useState('');
 const [loading,setLoading]=useState(true),[error,setError]=useState(''),[busy,setBusy]=useState(''),[added,setAdded]=useState<string[]>([]),[copied,setCopied]=useState('');
 const lock=useRef(false);const root=useRef<HTMLElement>(null);
 const base='/api/studio/soundtracks';
 const moods:Record<string,string>={all:t('Все настроения','All moods','全部氛围'),calm:t('Спокойное','Calm','舒缓'),uplifting:t('Позитивное','Uplifting','轻快'),energetic:t('Энергичное','Energetic','活力'),acoustic:t('Акустика','Acoustic','原声'),other:t('Другое','Other','其他')};
 async function load(){setError('');setLoading(true);try{const r=await fetch(base);if(!r.ok)throw Error();setTracks(await r.json())}catch{setError(t('Не удалось загрузить музыку. Попробуй ещё раз.','Could not load music. Try again.','无法加载音乐，请重试。'))}finally{setLoading(false)}}
 useEffect(()=>{void load();setAdded([])},[pid]);
 async function act(track:Track,favorite=false){if(lock.current)return;lock.current=true;setBusy(track.key);setError('');try{const r=await fetch(favorite?`${base}/${track.key}/favorite`:`/api/studio/projects/${pid}/soundtracks/${track.key}`,{method:favorite?'PUT':'POST',headers:{'Content-Type':'application/json'},...(favorite?{body:JSON.stringify({favorite:!track.favorite})}:{})});if(!r.ok){const body=await r.json();throw Error(body.detail)}if(favorite)setTracks(rows=>rows.map(v=>v.key===track.key?{...v,favorite:!v.favorite}:v));else{setAdded(ids=>[...ids,track.key]);await onChanged()}}catch(e){setError(e instanceof Error&&e.message==='asset_limit'?t('В проекте уже 20 материалов.','This project already has 20 assets.','项目已有 20 个素材。'):t('Не получилось выполнить действие. Попробуй ещё раз.','Could not complete the action. Try again.','操作未完成，请重试。'))}finally{setBusy('');lock.current=false}}
 async function copy(track:Track){try{await navigator.clipboard.writeText(track.attribution);setCopied(track.key)}catch{setError(t('Скопируй подпись вручную из блока «Автор и лицензия».','Copy the credit manually from Author and license.','请从作者与授权部分手动复制署名。'))}}
 const visible=tracks.filter(v=>(tab==='favorites'?v.favorite:v.origin===tab)&&(mood==='all'||v.mood===mood)&&(v.title+' '+v.artist).toLowerCase().includes(query.toLowerCase()));
 return <section className="soundtrack-library director-card" ref={root} aria-label={t('Подборка фоновой музыки','Background music collection','背景音乐精选')}>
 <header><div><h3><Music2 size={20}/> {t('Фоновая музыка','Background music','背景音乐')}</h3><p>{t('Слушай, сохраняй в избранное и используй в любом своём проекте.','Listen, save favorites and reuse in any of your projects.','试听、收藏并在任意项目中复用。')}</p></div><span className="soundtrack-badge">{t('Готовая подборка','Curated collection','精选曲库')}</span></header>
 <div className="soundtrack-tabs" role="group" aria-label={t('Раздел музыки','Music section','音乐分类')}>{[['curated',t('Подборка','Collection','精选')],['favorites',t('Избранное','Favorites','收藏')],['uploaded',t('Мои треки','My tracks','我的曲目')]].map(([id,label])=><button type="button" key={id} aria-pressed={tab===id} className={tab===id?'primary':'secondary'} onClick={()=>{setTab(id);setMood('all')}}>{label}</button>)}</div>
 <div className="soundtrack-filters"><label>{t('Поиск','Search','搜索')}<input type="search" value={query} onChange={e=>setQuery(e.target.value)} placeholder={t('Название или автор','Title or artist','曲名或作者')}/></label><label>{t('Настроение','Mood','氛围')}<select aria-label={t('Настроение','Mood','氛围')} value={mood} onChange={e=>setMood(e.target.value)}>{Object.entries(moods).map(([id,label])=><option key={id} value={id}>{label}</option>)}</select></label></div>
 {loading&&<p role="status">{t('Загружаю музыку…','Loading music…','正在加载音乐…')}</p>}
 {error&&<p role="alert">{error} <button type="button" className="secondary" onClick={()=>void load()}>{t('Обновить','Refresh','刷新')}</button></p>}
 {!loading&&!error&&!visible.length&&<p>{tab==='favorites'?t('Нажми звёздочку рядом с треком, чтобы сохранить его здесь.','Star a track to save it here.','点击曲目旁的星标即可收藏。'):tab==='uploaded'?t('Загруженная тобой музыка из всех твоих проектов появится здесь.','Your music uploads from all your projects appear here.','所有项目中上传的音乐都会显示在这里。'):t('По этим фильтрам треков нет.','No tracks match these filters.','没有符合筛选条件的曲目。')}</p>}
 <div className="soundtrack-grid">{visible.map(track=><article className="soundtrack-track" key={track.key}><div className="soundtrack-track-heading"><div><strong>{track.title}</strong><small>{track.artist}</small></div><button type="button" className="secondary soundtrack-star" disabled={!!busy} aria-pressed={track.favorite} aria-label={(track.favorite?t('Убрать из избранного: ','Remove favorite: ','取消收藏：'):t('В избранное: ','Favorite: ','收藏：'))+track.title} onClick={()=>void act(track,true)}><Star size={18} fill={track.favorite?'currentColor':'none'}/></button></div>
 <p className="soundtrack-meta">{moods[track.mood]} · {Math.floor(track.duration/60)}:{String(Math.floor(track.duration%60)).padStart(2,'0')}{track.bpm?` · ${track.bpm} BPM`:''}</p>
 {track.available?<audio aria-label={t('Прослушать ','Preview ','试听 ')+track.title} controls preload="none" src={`${base}/${track.key}/media`} onPlay={e=>{root.current?.querySelectorAll('audio').forEach(a=>{if(a!==e.currentTarget)a.pause()})}}/>:<p>{t('Трек пока недоступен.','Track currently unavailable.','曲目暂不可用。')}</p>}
 <button type="button" className={added.includes(track.key)?'secondary':'primary'} disabled={!!busy||!track.available||full||added.includes(track.key)} onClick={()=>void act(track)}>{added.includes(track.key)?<Check size={16}/>:<Plus size={16}/>} {busy===track.key?t('Сохраняю…','Saving…','保存中…'):added.includes(track.key)?t('В проекте','Added to project','已添加'):t('Добавить в проект','Add to project','添加到项目')}</button>
 {track.license&&<small>{t('Можно использовать с указанием автора','Use with artist attribution','使用时须署名')}</small>}
 <details><summary>{t('Автор и лицензия','Author and license','作者与授权')}{track.license?` · ${track.license}`:''}</summary><p className="soundtrack-credit">{track.attribution}</p>{track.license_url&&<p>{t('При публикации укажи автора — скопируй подпись ниже.','Credit the artist when publishing — copy the credit below.','发布时请署名，复制下方署名文本。')}</p>}<button type="button" className="secondary" onClick={()=>void copy(track)}><Copy size={14}/> {copied===track.key?t('Скопировано','Copied','已复制'):t('Скопировать подпись','Copy credit','复制署名')}</button>{track.source_url&&<> · <a href={track.source_url} target="_blank" rel="noreferrer">{t('Источник','Source','来源')}</a></>}</details>
 </article>)}</div>
 {full&&<p role="status">{t('Библиотека проекта заполнена: 20 материалов.','Project library is full: 20 assets.','项目素材库已满：20 个素材。')}</p>}
 {!!added.length&&<p role="status">{t('Трек в библиотеке, но ещё не в видео. Выберите его в поле «Композиция» выше и нажмите «Добавить музыку в финальное видео».','The track is in your library, not yet in the video. Select it in Track above and choose Add music to final video.','曲目已加入曲库，但尚未加入视频。请在上方选择该曲目并点击将音乐加入成片。')}</p>}
 </section>
}
