import { translate, contentLanguage } from './locale';
import {useState} from 'react';
import {musicAccents,musicLoopBoundaries} from './musicTiming';
import {calloutBars,cardBar,formatSeconds,progressBar,speedBar,speedText,type LayerWindow} from './layerTiming';
import type {Asset} from './MediaLibrary';
import type {Music} from './MusicEditor';
import type {Lang} from './types';
import type {VisualCard} from './VisualCardEditor';
import type {Cutaway} from './CutawayEditor';
import type {ExternalBroll} from './MediaLibrary';
type Clip={sound_effects?:{kind:string;at:number;gain_db:number}[];external_broll?:ExternalBroll|null;cutaway?:Cutaway|null;card?:VisualCard|null;id?:string;start:number;end:number;text:string;approved?:boolean;locked?:boolean;shot_type?:string;kinetic?:boolean;title_in?:number;title_out?:number;title_x?:number|null;kinetic_at?:number[];effect_at?:number;effect_end?:number;speed?:number|null;speed_end?:number|null;progress?:number;progress_at?:number;progress_end?:number};
export function TimelineTracks({clips,captions,subtitles,lang,onSelect,music,musicAsset,hasAudio=true}:{hasAudio?:boolean;musicAsset?:Asset;music?:Music|null;clips:Clip[];captions:{start:number;end:number;en:string;zh:string}[];subtitles:boolean;lang:Lang;onSelect:(i:number)=>void}){
 const t=(en: string, zh: string) => translate(lang, en, zh);
 const [view,setView]=useState<'draft'|'approved'>('draft');
 const pending=clips.filter(c=>c.approved===false).length;
 let cursor=0;const cuts=clips.flatMap((c,i)=>{if(view==='approved'&&c.approved===false)return [];const start=cursor;cursor+=c.end-c.start;return [{...c,cutaway:c.external_broll||c.cutaway,index:i,at:start,to:cursor}]});const duration=cursor;const scale=Math.max(24,600/Math.max(1,duration));const width=Math.max(600,duration*scale);
 const accents=(view==='approved'||pending===0)&&music&&musicAsset?.metadata.rhythm?musicAccents(musicAsset.metadata.rhythm.accents,musicAsset.metadata.duration,music.source_start,duration):[];
 const loops=(view==='approved'||pending===0)&&music&&musicAsset?musicLoopBoundaries(musicAsset.metadata.duration,music.source_start,duration):[];
 const soundLengths:Record<string,number>={chime:.6,click:.08,whoosh:.4};
 const roles:Record<string,string>={presenter:t('Presenter','讲解者'),close_up:t('Close-up','特写'),medium:t('Medium shot','中景'),broll:t('B-roll','补充画面'),document:t('Document','文档'),archive:t('Archival footage','档案影像'),news:t('News clip','新闻片段')};
 const spoken=contentLanguage(lang);
 const place=(at:number,window:LayerWindow)=>({left:(at+window.start)*scale,width:Math.max(4,(window.end-window.start)*scale)});
 const callouts=cuts.flatMap(c=>calloutBars(c).map((window,n)=>({c,window,n})));
 const cards=cuts.flatMap(c=>{const window=cardBar(c);return window?[{c,window}]:[]});
 const bars=cuts.flatMap(c=>{const window=progressBar(c);return window?[{c,window}]:[]});
 const speeds=cuts.flatMap(c=>{const window=speedBar(c);return window?[{c,window}]:[]});
 const showMusic=view==='approved'||pending===0;
 return <section className="timeline-tracks" aria-label={t('Director Timeline','导演时间线')}><h3>{t('Director Timeline','导演时间线')} · {duration.toFixed(1)}s</h3><div role="group" aria-label={t('Timeline view','时间线视图')}><button type="button" aria-pressed={view==='draft'} onClick={()=>setView('draft')}>{t('Proposed timeline','方案时间线')}</button><button type="button" aria-pressed={view==='approved'} onClick={()=>setView('approved')}>{t('Approved output','已批准成片')}</button></div><p>{view==='draft'?t('All proposed shots are visible. Amber shots still need approval and are excluded from rendering. Click a shot to review or edit it.','显示全部建议镜头。琥珀色镜头尚待批准，不会参与制作。点击镜头进行审核或编辑。'):t('Only approved shots appear here, at their final output times.','此处仅显示已批准镜头及其成片时间。')}</p>{music&&pending>0&&view==='draft'&&<p>{t('Music timing is shown in Approved output until all shots are approved.','所有镜头批准前，请在已批准成片视图中查看音乐时间。')}</p>}{music&&showMusic&&<p>{t('Music: dashed amber lines mark repeats; purple lines mark estimated accents.','音乐：琥珀色虚线标记循环点，紫线标记估计重音。')} {t('Edge smoothing','接点平滑')}: {music.loop_fade_ms||0} ms · {t('Fade in / out','淡入／淡出')}: {Math.min(music.fade_in,duration/2).toFixed(1)} / {Math.min(music.fade_out,duration/2).toFixed(1)}s{loops.length===80&&` · ${t('First 80 repeats shown','仅显示前 80 个循环点')}`}</p>}<div className="timeline-scroll"><div style={{width}}><div className="timeline-ruler">{Array.from({length:Math.ceil(duration)+1},(_,i)=><span key={i} style={{left:i*scale}}>{i%5===0?`${i}s`:'·'}</span>)}</div>
 <div className="timeline-row timeline-video"><strong>{t('Video','视频')}</strong>{cuts.map(c=><button type="button" className={c.approved===false?'pending-review':''} aria-label={`${c.index+1} · ${c.approved===false?t('Needs approval','待批准'):t('Approved','已批准')}`} key={c.id||c.index} onClick={()=>onSelect(c.index)} style={{left:c.at*scale,width:Math.max(4,(c.to-c.at)*scale)}} title={`${c.start.toFixed(1)}–${c.end.toFixed(1)}s → ${c.at.toFixed(1)}s`}>{c.locked?'🔒 ':c.approved===false?'○ ':''}{c.index+1} · {roles[c.shot_type||'']||t('Source','原片')}</button>)}</div>
 {callouts.length>0&&<div className="timeline-row timeline-callout"><strong>{t('Text','文字')}</strong>{callouts.map(({c,window,n})=>{const box=place(c.at,window);return <button type="button" key={`${c.id||c.index}-callout-${n}`} onClick={()=>onSelect(c.index)} style={box} title={`${c.text} · ${formatSeconds(window.start)}–${formatSeconds(window.end)}`}>{c.text}</button>})}</div>}
 <div className="timeline-row timeline-subtitles"><strong>{t('Subtitles','字幕')}</strong>{subtitles&&cuts.flatMap(c=>captions.flatMap((s,j)=>{const a=Math.max(c.start,s.start),b=Math.min(c.end,s.end);return b>a?[<button type="button" key={`${c.index}-${j}`} onClick={()=>onSelect(c.index)} style={{left:(c.at+a-c.start)*scale,width:Math.max(4,(b-a)*scale)}} title={s[spoken]}>{s[spoken]}</button>]:[]}))}</div>
 {cards.length>0&&<div className="timeline-row timeline-card"><strong>{t('Data cards','数据卡片')}</strong>{cards.map(({c,window})=>{const box=place(c.at,window);return <button type="button" key={c.id||c.index} onClick={()=>onSelect(c.index)} style={box} title={`${c.card!.title[spoken]} · ${formatSeconds(window.start)}–${formatSeconds(window.end)}`}>{c.card!.primary[spoken]||t('Untitled card','未命名卡片')}</button>})}</div>}
 {bars.length>0&&<div className="timeline-row timeline-progress"><strong>{t('Progress bar','进度条')}</strong>{bars.map(({c,window})=>{const box=place(c.at,window);return <button type="button" key={c.id||c.index} onClick={()=>onSelect(c.index)} style={box} title={`${formatSeconds(window.start)}–${formatSeconds(window.end)}`}>{t('Progress bar','进度条')}</button>})}</div>}
 {speeds.length>0&&<div className="timeline-row timeline-speed"><strong>{t('Speed','速度')}</strong>{speeds.map(({c,window})=>{const box=place(c.at,window);const label=speedText(c);return <button type="button" key={`${c.id||c.index}-speed`} onClick={()=>onSelect(c.index)} style={box} title={`${label} · ${formatSeconds(window.start)}–${formatSeconds(window.end)}`}>{label}</button>})}</div>}
 <div className="timeline-row timeline-audio"><strong>{t('Original audio','原始音轨')}</strong>{hasAudio&&cuts.map(c=><button type="button" key={c.id||c.index} onClick={()=>onSelect(c.index)} style={{left:c.at*scale,width:Math.max(4,(c.to-c.at)*scale)}}>{t('Source','原片')} {c.index+1}</button>)}</div>
 <div className="timeline-row timeline-broll"><strong>{t('B-roll','补充镜头')}</strong>{cuts.filter(c=>c.cutaway).map(c=><button type="button" key={c.id||c.index} onClick={()=>onSelect(c.index)} style={{left:(c.at+c.cutaway!.start)*scale,width:Math.max(4,(c.cutaway!.end-c.cutaway!.start)*scale)}}>{c.cutaway!.source_start.toFixed(1)}s →</button>)}</div>
 <div className="timeline-row timeline-effects"><strong>{t('Sound effects','音效')}</strong>{cuts.flatMap(c=>(c.sound_effects||[]).map((e,i)=><button type="button" key={`${c.index}-${i}`} onClick={()=>onSelect(c.index)} style={{left:(c.at+e.at)*scale,width:Math.max(2,scale*(soundLengths[e.kind]||.6))}} title={`${e.kind} · ${(c.at+e.at).toFixed(2)}–${(c.at+e.at+(soundLengths[e.kind]||.6)).toFixed(2)}s · ${e.gain_db} dB`}>{e.kind}</button>))}</div>
 <div className="timeline-row timeline-music"><strong>{t('Music','音乐')}</strong>{showMusic&&music&&duration>0&&<span style={{position:'absolute',left:0,width:duration*scale}}>{music.gain_db} dB · {loops.length?t('Repeating music','循环音乐'):t('Music bed','背景音乐')}</span>}{showMusic&&music?.levels&&music.levels.length>0&&duration>0&&<svg aria-label={t('Music volume curve','音乐音量曲线')} style={{position:'absolute',left:0,top:4,pointerEvents:'none'}} width={duration*scale} height={28}><polyline fill="none" stroke="#c2d767" strokeWidth={2} points={music.levels.map(p=>`${p.at*scale},${26-(p.gain_db+40)/34*24}`).join(' ')}/></svg>}{loops.map((at,i)=><span key={`loop-${i}`} title={`${t('Music repeats here','音乐在此循环')} ${at.toFixed(2)}s · ${music?.loop_fade_ms||0} ms`} style={{position:'absolute',left:at*scale,top:0,height:34,borderLeft:'2px dashed #f59e0b',pointerEvents:'none'}}/>)}{accents.map((at,i)=><span key={i} title={`${t('Estimated accent','估计重音')} ${at.toFixed(2)}s`} style={{position:'absolute',left:at*scale,top:18,height:16,borderLeft:'2px solid #8b5cf6',pointerEvents:'none'}}/>)}</div>
 </div></div></section>
}
